FerretDB/FerretDB

- README.md
Hi,
Just fixed up some of the grammar and typo fixes. Cool project, I noticed some issues using mongodb over the past few years so good to see.
> Grammar and Typo fixes

- internal/handlers/common/error.go
> [#19] Fix panic when no error present

- Dockerfile
- Makefile
> Build multi-arch Docker images.

- internal/handlers/handler.go
- internal/handlers/handler_test.go
- internal/handlers/shared/msg_dropdatabase.go
> Implement `dropDatabase` command.

- .github/actions/setup-go/action.yml
- .github/workflows/go.yml
Refs #122 
Extracted Go setup and caching to separate reusable action. Input and if statement was added until fuzz is treated in the same manner.
> Use composite GitHub Action for Go setup. (#122)

- CONTRIBUTING.md
This seems to be a typo. The title is self-explanatory
> CONTRIBTUING.md: fix "/user/.../" -> "/usr/.../"

- cmd/envtool/main.go
> Wait for PostgreSQL on `make env-up`.

- .github/workflows/containers_main.yml
- .gitignore
Build multi-arch image with GitHub Actions on the `main` branch.
Refs #70.
> Build Docker image with GitHub Actions.

- internal/handlers/handler.go
- internal/handlers/handler_test.go
- internal/handlers/shared/msg_hello.go
- internal/handlers/shared/query_cmd.go
- internal/util/testutil/path.go
> Support `hello` command.

- internal/handlers/handler.go
- internal/handlers/jsonb1/msg_createindexes.go
- internal/handlers/sql/msg_createindexes.go
> Add stub for `createindexes` command.

- go.mod
- internal/handlers/handler.go
- internal/handlers/handler_test.go
- internal/handlers/shared/msg_hostinfo.go
Closes #157 
Without `extra` field yet.
> Support basic `hostInfo` command.

- internal/handlers/handler_test.go
- internal/handlers/shared/msg_getlog.go
> Fix GetLog & add missed test for it.

- .github/workflows/containers.yml
- Use percona-platform/extract-docker-tag-action@v1 to extract the DOCKER_TAG environment variable
- Trigger build actions for PRs only and for tags
> Container builds for PRs and tags.

- Makefile
- internal/bson/bson_test.go
- internal/fjson/fjson_test.go
> Fix benchmarks

- .golangci.yml
- internal/handlers/msg_delete_test.go
- internal/handlers/msg_update_test.go
- internal/handlers/sql/convert_test.go
- internal/handlers/sql/sql_test.go
> Move handler tests

- internal/handlers/handler.go
- internal/handlers/handler_test.go
- internal/handlers/shared/msg_datasize.go
> Support `dataSize`

- internal/handlers/command.go
- internal/handlers/common/error.go
- internal/handlers/common/unimplemented.go
- internal/handlers/handler.go
- internal/handlers/jsonb1/msg_createindexes.go
- internal/handlers/jsonb1/msg_delete.go
- internal/handlers/jsonb1/msg_find_or_count.go
- internal/handlers/jsonb1/msg_insert.go
- internal/handlers/jsonb1/msg_update.go
- internal/handlers/jsonb1/where.go
- internal/handlers/msg_create.go
- internal/handlers/msg_datasize.go
- internal/handlers/msg_drop.go
- internal/handlers/msg_dropdatabase.go
- internal/handlers/msg_getlog.go
- internal/handlers/msg_getparameter.go
- internal/handlers/msg_listcollections.go
- internal/handlers/msg_listdatabases.go
- internal/handlers/query_cmd.go
- internal/handlers/sql/msg_createindexes.go
- internal/handlers/sql/msg_delete.go
- internal/handlers/sql/msg_find_or_count.go
- internal/handlers/sql/msg_insert.go
- internal/handlers/sql/msg_update.go
- internal/handlers/sql/where.go
- internal/types/document.go
> Add helper for checking for unimplemented fields

- cmd/envtool/main.go
- cmd/ferretdb/main.go
- internal/clientconn/listener.go
- internal/clientconn/listener_metrics.go
- internal/handlers/handler.go
- internal/handlers/handler_metrics.go
- internal/util/ctxutil/ctxutil.go
> Add more metrics

- internal/handlers/msg_listcollections.go
- internal/handlers/msg_listdatabases.go
> Ignore `authorizedXXX` parameters for now

- internal/handlers/common/params.go
- internal/handlers/sql/where.go
> Use safe type assertions for inputs

- Makefile
- cmd/fuzztool/fuzztool.go
Copy internal/package/testdata/fuzz/Func/HEX files under right paths.
Refs #326.
> Fix seed fuzz corpus collection

- .github/workflows/go.yml
- Makefile
- internal/handlers/common/error.go
- internal/handlers/handler.go
- internal/handlers/handler_fuzz_test.go
- internal/handlers/handler_test.go
- internal/util/testutil/fuzz.go
> Add fuzzing tests for handlers

- .golangci-required.yml
- .golangci.yml
- tools/go.mod
- tools/go.sum
- tools/tools.go
> Add `bin/task` to tools

- Taskfile.yml
> Fix Taskfile

- internal/handlers/common/error.go
- internal/handlers/common/errorcode_string.go
- internal/handlers/common/projection.go
For https://github.com/FerretDB/FerretDB/pull/377  and https://github.com/FerretDB/FerretDB/pull/382
> Projection add error codes when inclusion and exclusion is used 

- .github/workflows/docker.yml
- .github/workflows/go.yml
- Taskfile.yml
Module proxy is faster than GitHub's cache.
> Do not cache modules

- .github/workflows/go.yml
- internal/handlers/handler_fuzz_test.go
- internal/handlers/handler_test.go
> Fix more fluky tests

- internal/handlers/common/filter.go
- internal/handlers/common/limit.go
- internal/handlers/common/params.go
- internal/handlers/common/sort.go
- internal/handlers/handler_test.go
- internal/handlers/jsonb1/msg_count.go
- internal/handlers/jsonb1/msg_delete.go
- internal/handlers/jsonb1/msg_find.go
- internal/handlers/msg_delete_test.go
> Handle any number type for `limit`

- .github/workflows/integration.yml
- Taskfile.yml
- integration/commands_replication_test.go
- internal/handlers/handler_test.go
- internal/handlers/pg/command.go
- internal/handlers/pg/msg_hello.go
- internal/handlers/pg/msg_ismaster.go
- internal/handlers/pg/query_cmd.go
> Tweak `hello`/`ismaster`/`isMaster` responses

- internal/handlers/pg/msg_hello.go
- internal/handlers/pg/msg_ismaster.go
- internal/handlers/pg/msg_ping.go
`ping`, `hello`, `isMaster` commands now check database connection.
> Ping database in some commands

- integration/basic_test.go
- integration/helpers.go
- integration/query_comparision_test.go
- integration/shareddata/composites.go
- integration/shareddata/scalars.go
- internal/handlers/handler_fuzz_test.go
Add test data for documents and arrays.
Fix NaNs comparision.
Closes #411.
> Integration tests improvements

- integration/helpers.go
- integration/query_bitwise_test.go
> Add test stub for bitwise operators

- go.mod
- integration/commands_diagnostic_test.go
- integration/helpers.go
- internal/handlers/handler_test.go
- internal/handlers/pg/msg_hostinfo.go
> Add tests for more diagnostic commands

- integration/query_comparision_test.go
- internal/handlers/common/filter.go
> Add tests for `null` values

- integration/query_evalution_test.go
> Skip one test for now

- integration/query_comparision_test.go
- internal/handlers/common/filter.go
> Add support for `$ne` operator

- internal/handlers/pg/command.go
- internal/handlers/pg/msg_createindexes.go
- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_find.go
- internal/handlers/pg/msg_findandmodify.go
- internal/handlers/pg/msg_insert.go
- internal/handlers/pg/msg_update.go
> Add basic `findAndModify` implementation

- internal/handlers/pg/msg_listdatabases.go
> Implement `nameOnly` for `listDatabases`

- internal/clientconn/conn.go
- internal/handlers/common/commands.go
- internal/handlers/common/msg_commands.go
- internal/handlers/dummy/dummy_test.go
> Add `debug` and `panic` msg handlers to `Command` map

- integration/basic_test.go
- internal/handlers/common/filter.go
- internal/handlers/pg/fetch.go
- internal/handlers/pg/msg_count.go
- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_find.go
- internal/handlers/pg/msg_findandmodify.go
- internal/handlers/pg/msg_update.go
> Support `$comment` query operator

- integration/basic_test.go
- integration/query_array_test.go
- integration/query_element_test.go
- integration/query_projection_test.go
- integration/shareddata/scalars.go
- internal/bson/double_test.go
- internal/fjson/double.go
- internal/fjson/double_test.go
- internal/util/testutil/equal.go
- internal/util/testutil/equal_test.go
> Improve negative zero handling

- integration/query_evaluation_test.go
It fails the same way on Linux.
> Skip test on all ARM64 OSes

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/integration.yml
- .golangci.yml
- .markdownlint.yml
- docker-compose.yml
> Use `"` instead of `'` in all .yml files

- integration/update_test.go
- internal/handlers/common/update.go
> Support `$unset` field update operator

- internal/clientconn/conn.go
I made an ugly bug in #650, and in fact, proxy responses haven't been logged since then.
This is a fix for that bug.
> Fix a bug with proxy response logs

- docker-compose.yml
> Disable "free monitoring" to simplify tests

- .github/workflows/docker.yml
It described a thing that is no longer present.
> Remove outdated comment

- Taskfile.yml
> Skip `-race` flag on Windows

- internal/fjson/object_id.go
- internal/tjson/object_id.go
- internal/tjson/tjson.go
- internal/tjson/tjson_test.go
Add function that will be used later.
Simplify code.
> `tjson` improvements

- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_update.go
> Unify similar code in `pg` handler

- .markdownlint.yml
- Taskfile.yml
- build/deps/tigris.Dockerfile
- build/deps/tigris_fdb.Dockerfile
- build/deps/tigris_typesense.Dockerfile
- docker-compose.yml
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
Add Docker Compose configuration.
Update deps.
Reformat files.
> Add Tigris environment

- integration/commands_administration_test.go
- integration/commands_freemonitoring_test.go
- internal/handlers/common/msg_getfreemonitoringstatus.go
- internal/handlers/common/msg_listcommands.go
- internal/handlers/dummy/msg_getfreemonitoringstatus.go
- internal/handlers/handlers.go
- internal/handlers/pg/msg_getfreemonitoringstatus.go
- internal/handlers/tigris/msg_getfreemonitoringstatus.go
> Implement `getFreeMonitoringStatus` stub

- .github/workflows/conform-pr.yml
> Update `conform-pr` action

- internal/handlers/common/update.go
> Add TODO item

- .github/workflows/docker.yml
> Install QEMU for building Docker images

- integration/commands_administration_test.go
- integration/commands_diagnostic_test.go
- integration/commands_freemonitoring_test.go
- integration/setup.go
- integration/shareddata_test.go
> Export fields

- Taskfile.yml
- build/deps/tigris.Dockerfile
- build/deps/tigris_fdb.Dockerfile
- build/deps/tigris_main.Dockerfile
- build/deps/tigris_typesense.Dockerfile
- docker-compose.yml
> Update Tigris version

- .github/workflows/integration.yml
- docker-compose.yml
> Test with the `main` version of Tigris too

- integration/embedded_test.go
- integration/tigris/embedded_test.go
Those a databases, not collections.
> Fix invalid variable names

- integration/helpers.go
- internal/util/testutil/dump.go
- internal/util/testutil/equal.go
They will be used by the next PR.
> Add a few testing helpers

- integration/setup.go
- internal/clientconn/conn.go
- internal/handlers/pg/pgdb/pool.go
- internal/util/testutil/pg.go
> Disable logs during test setup

- Taskfile.yml
- cmd/envtool/main.go
> Restart development containers faster

- internal/handlers/pg/msg_create.go
- internal/handlers/pg/msg_insert.go
- internal/handlers/pg/pgdb/collections.go
- internal/handlers/pg/pgdb/databases.go
- internal/handlers/pg/pgdb/insert.go
- internal/handlers/pg/pgdb/pgdb.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/pg/pgdb/pool_test.go
- internal/handlers/pg/pgdb/query_documents.go
- internal/handlers/pg/pgdb/schemas.go
- internal/handlers/pg/pgdb/settings.go
- internal/handlers/pg/pgdb/tables.go
- internal/util/testutil/pg.go
This PR is preparation for #808.
It covers more cases with transactions, e.g. `msgInsert` and `msgCreate`.
It doesn't cover all the possible places, it's rather timeboxed.
> Cover more logic in transactions

- Taskfile.yml
It is easier to debug them this way.
> Stop tests on the first data race

- integration/basic_test.go
- integration/commands_administration_test.go
- integration/commands_diagnostic_test.go
- integration/commands_freemonitoring_test.go
- integration/commands_replication_test.go
- integration/delete_test.go
- integration/embedded_test.go
- integration/findandmodify_test.go
- integration/query_array_test.go
- integration/query_bitwise_test.go
- integration/query_comparison_test.go
- integration/query_compat_test.go
- integration/query_element_test.go
- integration/query_evaluation_test.go
- integration/query_logical_test.go
- integration/query_projection_test.go
- integration/query_test.go
- integration/setup/setup.go
- integration/shareddata_test.go
- integration/tigris/embedded_test.go
- integration/tigris/shareddata_test.go
- integration/tigris/smoke_test.go
- integration/update_compat_test.go
- integration/update_field_test.go
- integration/update_test.go
> Extract integration tests setup to own package

- .golangci-new.yml
- .golangci.yml
> Tweak linter settings

- internal/handlers/common/update.go
- internal/handlers/pg/msg_findandmodify.go
> Ensure that update operators are in sync

- Taskfile.yml
- integration/Taskfile.yml
- integration/basic_test.go
- integration/commands_administration_test.go
- integration/delete_test.go
- integration/embedded_test.go
- integration/findandmodify_test.go
- integration/query_array_test.go
- integration/query_bitwise_test.go
- integration/query_comparison_test.go
- integration/query_element_test.go
- integration/query_evaluation_test.go
- integration/query_logical_test.go
- integration/query_projection_test.go
- integration/query_test.go
- integration/setup/common.go
- integration/setup/setup.go
- integration/update_field_test.go
- integration/update_test.go
> Add `SkipForTigris` helper, use it

- .github/workflows/integration.yml
- Taskfile.yml
- integration/compattestcaseresulttype_string.go
- integration/helpers.go
- integration/setup/common.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/shareddata/composites.go
- integration/shareddata/scalars.go
- integration/shareddata/shareddata.go
> Add setup for compatibility tests

- integration/update_field_compat_test.go
Refs #673.
Without `skip`, it fails with
```
--- FAIL: TestUpdateFieldCompatInc/EmptyPath/TestUpdateFieldCompatInc_EmptyPath_Doubles/double-zero (0.50s)
update_field_compat_test.go:41:
Error Trace:	.../FerretDB/integration/update_compat_test.go:81
Error:      	Not equal:
expected: mongo.WriteException(mongo.WriteException{WriteConcernError:(*mongo.WriteConcernError)(nil), WriteErrors:mongo.WriteErrors{mongo.WriteError{Index:0, Code:56, Message:"An empty update path is not valid.", Details:bson.Raw(nil), Raw:bson.Raw(nil)}}, Labels:[]string(nil), Raw:bson.Raw(nil)})
actual  : mongo.CommandError(mongo.CommandError{Code:0, Message:"connection(127.0.0.1:60634[-141]) socket was unexpectedly closed: EOF", Labels:[]string{"NetworkError", "RetryableWriteError"}, Name:"", …
```
> Add test case for an empty update path

- Taskfile.yml
- integration/Taskfile.yml
- integration/setup/common.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/shareddata_test.go
Refs #914.
Assignee, Labels, Project and project's Sprint fields.
> Add back `task env-data`

- integration/findandmodify_test.go
- integration/query_test.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/shareddata/shareddata.go
> Insert test data in random order

- build/deps/tigris.Dockerfile
Closes #993.
Assignee, Labels, Project and project's Sprint fields.
> Bump Tigris Docker image to alpha.26

- integration/helpers.go
- internal/bson/bson.go
- internal/clientconn/conn.go
- internal/fjson/fjson.go
- internal/handlers/common/params.go
- internal/handlers/common/update.go
- internal/handlers/dummy/dummy.go
- internal/handlers/pg/pgdb/collections.go
- internal/handlers/pg/pgdb/databases.go
- internal/types/types.go
- internal/util/testutil/equal.go
To make future PRs smaller.
We do not require 1.19 yet.
Assignee, Labels, Project and project's Sprint fields.
> Reformat with Go 1.19

- integration/delete_compat_test.go
- integration/helpers.go
- integration/query_compat_test.go
- integration/update_compat_test.go
Closes #999.
Assignee, Labels, Project and project's Sprint fields.
> Add compatibility `delete` test for Tigris

- Taskfile.yml
> Fix `Run linters` job in Taskfile.yml

- integration/delete_compat_test.go
- integration/go.mod
- integration/helpers.go
- integration/query_compat_test.go
- integration/update_compat_test.go
> Expose `delete` problem

- integration/update_field_compat_test.go
- internal/handlers/tigris/msg_update.go
> Fix `update` operation for Tigris handler

- build/deps/tigris.Dockerfile
There are some helpful fixes there (e.g. for validation of objects).
> Bump Tigris version to 1.0.0-alpha.29

- integration/commands_administration_test.go
- internal/handlers/tigris/fetch.go
- internal/handlers/tigris/msg_datasize.go
- internal/handlers/tigris/msg_dbstats.go
> Implement `MsgDataSize` for Tigris

- .github/workflows/integration.yml
- integration/helpers.go
- integration/query_logical_test.go
> Add integration tests for logical operators

- .golangci-new.yml
> Enable `errorlint` for new code

- internal/handlers/tigris/msg_delete.go
> Add missing TODO

- CONTRIBUTING.md
- Dockerfile
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- internal/types/regex.go
- tools/check.go
- tools/go.mod
- tools/go.sum
- tools/old.go
- tools/tools.go
- website/package-lock.json
- website/package.json
> Switch to Go 1.19, bump dependencies

- internal/handlers/pg/msg_listcollections.go
> Add transaction to `pg`'s `msg_listcollections`

- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_update.go
- internal/handlers/pg/pgdb/insert.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/pg/pgdb/pool_test.go
- internal/handlers/pg/pgdb/query_test.go
> Use transaction in more `pgdb` functions

- CONTRIBUTING.md
- Taskfile.yml
* document `task env-reset`;
* mention useful `GOFLAGS`.
Do not merge until everyone approved it.
> Improve contributing guidelines

- website/package-lock.json
- website/package.json
> Add local search plugin

- internal/handlers/common/filter.go
> Simplify / unify similar cases

- Dockerfile
> Use Go 1.19.2

- .github/PROCESS.md
- Dockerfile
- integration/Taskfile.yml
- integration/commands_administration_test.go
- integration/setup/setup_compat.go
- integration/shareddata_test.go
It should be more reliable now.
Also, improve process docs.
> Improve `task env-data`

- .github/mergify.yml
This should remove duplicates, making an output nicer.
> Remove implicit mergify rules

- internal/handlers/tigris/msg_insert.go
- internal/handlers/tigris/msg_update.go
- internal/handlers/tigris/tigrisdb/insert.go
- internal/handlers/tigris/tigrisdb/update.go
> Call data document validation when insert or update documents in Tigris

- cmd/envtool/main.go
- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/commands_administration_test.go
- integration/setup/common.go
- internal/clientconn/conn.go
- internal/clientconn/conninfo/conn_info.go
- internal/clientconn/connmetrics/conn_metrics.go
- internal/clientconn/connmetrics/conn_metrics_test.go
- internal/clientconn/connmetrics/listener_metrics.go
- internal/handlers/common/error.go
- internal/handlers/common/error_command.go
- internal/handlers/common/error_write.go
- internal/handlers/common/msg_aggregate.go
- internal/handlers/common/serverstatus.go
- internal/handlers/common/update.go
- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_getlog.go
- internal/handlers/pg/pgdb/pgdb_test.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/registry/registry.go
- internal/handlers/tigris/msg_delete.go
- internal/util/state/state.go
- internal/util/telemetry/reporter.go
> Collect command metrics in telemetry

- internal/clientconn/conn.go
- internal/clientconn/connmetrics/conn_metrics.go
- internal/handlers/common/error.go
- internal/handlers/common/error_command.go
- internal/handlers/common/error_write.go
- internal/handlers/common/msg_aggregate.go
- internal/handlers/common/serverstatus.go
- internal/handlers/common/unimplemented.go
- internal/handlers/common/update.go
- internal/util/telemetry/reporter.go
> Include info about unimplemented arguments

- integration/commands_administration_test.go
- integration/go.mod
> Do not compare error strings

- CHANGELOG.md
- website/docs/quickstart_guide/macos.md
- website/docs/quickstart_guide/rpm.md
- website/docs/quickstart_guide/windows.md
> Add text for empty pages

- .github/workflows/docs.yml
> Setup `lfs-warning` GitHub Action check

- build/deps/tigris.Dockerfile
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
> Bump Tigris

- internal/handlers/pg/pjson/pjson.go
- internal/types/fjson/fjson.go
> Remove unsupported NaN and Inf from pjson package documentation

- .github/workflows/conform-pr.yml
- Dockerfile
- README.md
- cmd/ferretdb/main.go
- internal/util/telemetry/reporter.go
- website/docs/quickstart_guide/docker.md
> Use environment variables for configuration

- internal/handlers/pg/msg_listcollections.go
- internal/handlers/tigris/msg_listcollections.go
- website/docs/Reference/supported_commands.md
> Start supported commands table

- build/.trivyignore
> Ignore website problems for now

- website/docs/reference/supported_commands.md
> Add aggregation section (collection stages) to the docs

- website/docs/reference/supported_commands.md
> Add query and write operation commands to the docs

- website/docs/reference/supported_commands.md
> Reorganize a list of supported commands

- integration/insert_compat_test.go
> Use `primitive.Regex` to test that regex `_id` is not allowed

- website/docs/reference/supported_commands.md
> Add user management commands to the docs

- website/docs/basic_operations/index.md
- website/docs/basic_operations/read.md
- website/docs/basic_operations/update.md
- website/docs/understanding_ferretdb.md
> Add documentation for embedded/nested documents query

- website/docs/reference/supported_commands.md
> Add authentication and role management commands to the docs

- internal/wire/records_test.go
> Add path to record loading error message

- website/docs/reference/supported_commands.md
> Add section for diagnostic command `buildInfo` and `collStats`

- website/docs/reference/supported_commands.md
> Add session and free monitoring commands to the docs

- README.md
- website/docs/intro.md
- website/docusaurus.config.js
> Add Mastodon links

- internal/bson/bson.go
- internal/handlers/pg/pjson/pjson.go
- internal/handlers/tigris/tjson/tjson.go
- internal/types/fjson/fjson.go
- internal/types/types.go
> Update documentation for types, add aliases

- .github/workflows/conform-pr.yml
> Fix `Conform PR` workflow

- internal/handlers/common/error.go
- internal/handlers/pg/msg_create.go
- internal/handlers/pg/msg_insert.go
- internal/handlers/pg/pgdb/collections.go
- internal/handlers/pg/pgdb/databases.go
- internal/handlers/pg/pgdb/insert.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/pg/pgdb/query_test.go
- internal/handlers/pg/pgdb/settings.go
- internal/handlers/pg/pgdb/transactions.go
> Add `InTransactionRetry` helper

- website/docs/reference/operators/comparison-operators.md
- website/docs/reference/operators/element-operators.md
> Add documentation for element query operators

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/chore.yml
- .github/PULL_REQUEST_TEMPLATE.md
Closes #1160.
With this PR I wanted to add `Definition of Done` field to `chore` issue template.
Also, `Environment` field was added to `bug` issue template.
> Update issue templates

- .github/workflows/integration.yml
- build/deps/tigris.Dockerfile
- cmd/envtool/envtool.go
> Bump Tigris version

- integration/update_field_compat_test.go
- internal/handlers/common/update.go
> Fix unset document being updated by invalid value of $inc

- README.md
- Taskfile.yml
- cmd/envtool/envtool.go
- cmd/envtool/ports.go
- cmd/ferretdb/main.go
- docker-compose.yml
- ferretdb/ferretdb_test.go
- integration/embedded_test.go
- integration/setup/common.go
- internal/handlers/common/msg_connectionstatus.go
- internal/util/testutil/pg.go
- website/docs/quickstart_guide/docker.md
> Enable authentication in PostgreSQL

- .dockerignore
> Fix Docker build

- Taskfile.yml
- internal/handlers/pg/msg_collstats.go
- internal/handlers/pg/msg_count.go
- internal/handlers/pg/msg_create.go
- internal/handlers/pg/msg_datasize.go
- internal/handlers/pg/msg_dbstats.go
- internal/handlers/pg/msg_delete.go
- internal/handlers/pg/msg_drop.go
- internal/handlers/pg/msg_dropdatabase.go
- internal/handlers/pg/msg_explain.go
- internal/handlers/pg/msg_find.go
- internal/handlers/pg/msg_findandmodify.go
- internal/handlers/pg/msg_hello.go
- internal/handlers/pg/msg_insert.go
- internal/handlers/pg/msg_ismaster.go
- internal/handlers/pg/msg_listcollections.go
- internal/handlers/pg/msg_listdatabases.go
- internal/handlers/pg/msg_ping.go
- internal/handlers/pg/msg_serverstatus.go
- internal/handlers/pg/msg_update.go
- internal/handlers/pg/pg.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/registry/registry.go
- internal/handlers/tigris/tigrisdb/databases.go
> Add stub for getting client-specific connection

- integration/insert_compat_test.go
> Add compat tests for `InsertOne` in addition to `InsertMany`

- .textlintignore
- CHANGELOG.md
- build/version/version.go
- cmd/ferretdb/main.go
- integration/query_compat_test.go
- internal/clientconn/listener.go
- internal/handlers/common/limit.go
- internal/handlers/pg/msg_explain.go
- internal/handlers/tigris/msg_explain.go
- website/blog/_guide/template.md
- website/docs/basic_operations/update.md
- website/docs/reference/operators/array-operators.md
- website/docs/reference/operators/comparison-operators.md
- website/docs/reference/operators/element-operators.md
- website/docs/reference/operators/logical-operators.md
- website/docs/reference/supported_commands.md
- website/docs/security.md
> Add documentation, prepare release

- CONTRIBUTING.md
- website/docs/flags.md
- website/docs/operation_modes.md
- website/docs/reference/glossary.md
- website/docs/security.md
> Add documentation about CLI flags and environment variables

- .gitattributes
- .github/workflows/docker.yml
- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- .github/workflows/go.yml
- .github/workflows/integration.yml
- .github/workflows/packages.yml
- .github/workflows/security.yml
- website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
- website/blog/2022-10-12-contribute_to_ferretdb_on_windows.md
- website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
- website/blog/authors.yml
(and test Cloudflare Pages deployment)
Deployment URL is visible in logs:
We might make it more accessible later.
> Reformat documentation

- internal/bson/array.go
- internal/handlers/common/distinct.go
- internal/handlers/common/error_write.go
- internal/handlers/common/msg_connectionstatus.go
- internal/handlers/pg/msg_find.go
- internal/handlers/pg/msg_getlog.go
- internal/handlers/pg/msg_listcollections.go
- internal/handlers/pg/msg_listdatabases.go
- internal/handlers/pg/msg_update.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/pg/pjson/array.go
- internal/handlers/tigris/msg_find.go
- internal/handlers/tigris/msg_getlog.go
- internal/handlers/tigris/msg_listcollections.go
- internal/handlers/tigris/msg_listdatabases.go
- internal/handlers/tigris/msg_update.go
- internal/handlers/tigris/tjson/array.go
- internal/types/array.go
- internal/types/array_test.go
- internal/util/logging/buffer.go
- internal/wire/op_msg.go
- tools/checkswitch/testdata/testdata.go
In this PR I remove `error` from the `Append` result parameters as it's always nil.
> Simplify `types.Array` `Append` signature

- cmd/envtool/envtool.go
- internal/handlers/pg/msg_findandmodify.go
- internal/handlers/pg/pg.go
- internal/handlers/pg/pgdb/pgdb_test.go
- internal/handlers/pg/pgdb/pool.go
- internal/handlers/tigris/msg_collstats.go
- internal/handlers/tigris/msg_count.go
- internal/handlers/tigris/msg_create.go
- internal/handlers/tigris/msg_datasize.go
- internal/handlers/tigris/msg_dbstats.go
- internal/handlers/tigris/msg_delete.go
- internal/handlers/tigris/msg_distinct.go
- internal/handlers/tigris/msg_drop.go
- internal/handlers/tigris/msg_dropdatabase.go
- internal/handlers/tigris/msg_explain.go
- internal/handlers/tigris/msg_find.go
- internal/handlers/tigris/msg_findandmodify.go
- internal/handlers/tigris/msg_getlog.go
- internal/handlers/tigris/msg_hello.go
- internal/handlers/tigris/msg_insert.go
- internal/handlers/tigris/msg_ismaster.go
- internal/handlers/tigris/msg_listcollections.go
- internal/handlers/tigris/msg_listdatabases.go
- internal/handlers/tigris/msg_ping.go
- internal/handlers/tigris/msg_update.go
- internal/handlers/tigris/tigris.go
- internal/handlers/tigris/tigrisdb/tigrisdb.go
- internal/handlers/tigris/tigrisdb/tigrisdb_test.go
> Remove lazy connection pools

- website/docs/reference/supported_commands.md
Please keep them this way until #1846 is resolved.
> Reformat Markdown tables

- .github/ISSUE_TEMPLATE/chore.yml
- .github/PROCESS.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Address two common problems:
* comments are not being updated;
* the Tigris handler is being forgotten about.
> Update development documentation

- website/blog/2021-11-05-mangodb-overwhelming-enthusiasm.md
- website/blog/2021-12-01-mangodb-has-a-new-name.md
- website/blog/2021-12-07-mongodb-compatibility.md
- website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
- website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
- website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
- website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
- website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
- website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
- website/blog/2022-08-23-open-source-is-in-danger.md
- website/blog/2022-09-20-how-to-contribute-to-open-source-2022.md
- website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
- website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
- website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
- website/blog/2022-10-12-contribute_to_ferretdb_on_windows.md
- website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
- website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
- website/blog/2022-11-11-new-release-ferretdb-0_6_1.md
- website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
- website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
- website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
- website/blog/2022-12-23-ferretdb-new-release-with-tls.md
- website/blog/2023-01-04-ferretdb-beta-version-authentication.md
- website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
- website/docs/reference/_category_.json
- website/docusaurus.config-blog.js
- website/docusaurus.config.js
- website/static/img/logo_dark.jpg
- website/static/img/logo_dark.png
> Reformat blog and documentation setup

- internal/clientconn/connmetrics/conn_metrics.go
- internal/util/telemetry/reporter.go
- website/docs/telemetry.md
Not all arguments are query operators.
> Clarify what command statistics we gather

- website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
- website/static/img/blog/ferretdb-query-pushdown.jpg
Closes FerretDB/engineering#17
> Add blog post on "How FerretDB fetches data (About query pushdown)"

- Dockerfile
- Taskfile.yml
- build/version/version.go
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- internal/handlers/registry/hana.go
- internal/handlers/registry/registry_test.go
> Ensure that we don't import extra dependencies

- website/docs/flags.md
- website/docs/quickstart_guide/debian.md
It was asked by a community member.
> Mention that there is no configuration file

- build/version/version.go
- internal/handlers/common/update.go
- internal/handlers/pg/msg_explain.go
- internal/handlers/pg/pgdb/pgdb_test.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/pg/pgdb/query_iterator.go
- internal/handlers/pg/pgdb/query_test.go
- internal/handlers/tigris/tigrisdb/insert.go
- internal/types/array_iterator.go
- internal/types/array_iterator_test.go
- internal/types/document_iterator.go
- internal/types/document_iterator_test.go
- internal/types/document_test.go
- internal/util/debugbuild/debugbuild.go
- internal/util/debugbuild/debugbuild_off.go
- internal/util/debugbuild/debugbuild_on.go
- internal/util/debugbuild/debugbuild_test.go
- internal/util/iterator/iterator.go
Needed for aggregation pipelines.
> Make iterator interface more strict

- .github/PROCESS.md
- CHANGELOG.md
- internal/handlers/pg/msg_aggregate.go
- internal/handlers/pg/msg_saslstart.go
And fix a couple of tiny bugs while I'm on it :)
> Prepare v0.9.0 release

- README.md
- website/docs/quickstart_guide/docker.md
> Fix broken link

- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/common.go
- internal/handlers/registry/registry.go
> Remove unused parameter

- .github/workflows/conform-pr.yml
- .github/workflows/docker.yml
- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- .github/workflows/go.yml
- .github/workflows/integration.yml
Do not run everything on every small push.
> Tweak CI settings

- integration/commands_administration_test.go
- internal/handlers/pg/msg_explain.go
- internal/types/document_validation_test.go
- internal/types/path.go
- internal/types/path_test.go
- internal/util/testutil/path_test.go
> Rename function, add TODO

- integration/query_comparison_compat_test.go
- integration/query_compat_test.go
> Remove `skipTigrisPushdown` from tests

- .github/workflows/docker.yml
> Build multiple Docker images for git tags

- build/version/version.go
- integration/shareddata/scalars.go
- internal/clientconn/conn.go
- internal/clientconn/conninfo/conn_info.go
- internal/clientconn/conninfo/conn_info_test.go
- internal/handlers/pg/pgdb/query_test.go
- internal/types/object_id.go
- internal/types/object_id_test.go
Extracted from #1769.
Closes #1733.
> Store cursors in `ConnInfo`

- .github/workflows/docker.yml
- Dockerfile
> Bump Go to 1.19.6

- .github/dependabot.yml
- .github/workflows/integration.yml
- Taskfile.yml
- build/deps/cockroach.Dockerfile
- build/deps/docusaurus-docs.Dockerfile
- build/deps/ferretdb-textlint.Dockerfile
- build/deps/ferretdb-wrangler.Dockerfile
- build/deps/postgres.Dockerfile
- build/deps/tigris.Dockerfile
- docker-compose.yml
Also remove unsupported CockroachDB.
> Bump more dependencies

- .github/dependabot.yml
- build/deps/trivy.Dockerfile
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
> Bump more deps, update Dependabot config

- internal/handlers/pg/msg_explain.go
- internal/handlers/pg/pg.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/registry/registry.go
- internal/handlers/registry/tigris.go
- internal/handlers/tigris/msg_explain.go
- internal/handlers/tigris/tigris.go
- internal/handlers/tigris/tigrisdb/query.go
No need to carry additional flag.
> Simplify pushdown disabling logic

- internal/handlers/common/find.go
- internal/handlers/common/msg_getmore.go
- internal/handlers/common/msg_listcommands.go
- internal/handlers/commonerrors/error.go
- internal/handlers/commonerrors/errorcode_string.go
- internal/handlers/dummy/msg_getmore.go
- internal/handlers/handlers.go
- internal/handlers/pg/msg_getmore.go
- internal/handlers/tigris/msg_getmore.go
- website/docs/reference/supported_commands.md
> Extract more `find` command parameters

- build/deps/tigris.Dockerfile
> Bump Tigris version to `1.0.0-beta.38`

- website/docusaurus.config-blog.js
- website/docusaurus.config.js
Closes FerretDB/engineering#32.
> Set up analytics for documentation and blog

- tools/go.mod
- tools/go.sum
Security / Security scan is failing https://github.com/FerretDB/FerretDB/actions/runs/4219315955/jobs/7324566219
```
tools/go.mod (gomod)
====================
Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                            Title                            │
├──────────────────┼────────────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-41723 │ LOW      │ 0.6.0             │ 0.7.0         │ [http2/hpack: avoid quadratic complexity in hpack …
```
> Bump `golang.org/x/net` version to 0.7.0 in `tools/go.mod`

- ferretdb/ferretdb_test.go
With the current approach, it's not possible to copy-paste examples from https://pkg.go.dev/github.com/FerretDB/FerretDB/ferretdb as they don't give references to the library.
In this PR the tests are not included into the same package, and will provide better examples for godocs.
> Embedded FerretDB documentation - examples improvements

- internal/handlers/common/update.go
- internal/types/document.go
- internal/types/document_test.go
> Simplify fields sorting, add TODO

- integration/update_array_compat_test.go
- internal/handlers/common/update.go
- internal/handlers/common/update_array_operators.go
- website/docs/reference/supported_commands.md
> Add `$pullAll` array update operator

- integration/embedded_test.go
- integration/setup/test_helpers.go
This fixes bug in `SkipForTigrisWithReason`.
> Fix `SkipForTigrisWithReason` helper

- website/blog/2023-02-28-ferretdb-release-0-9-2.md
- website/static/img/blog/ferretdb_v0.9.2.jpg
> Add blog post on FerretDB v0.92

- integration/query_array_compat_test.go
- integration/query_comparison_compat_test.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/pg/pgdb/query_test.go
- internal/handlers/tigris/tigrisdb/query.go
- internal/handlers/tigris/tigrisdb/query_test.go
> Temporarily remove pushdown for dot notation

- .github/ISSUE_TEMPLATE/bug.yml
- CONTRIBUTING.md
- Dockerfile
- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- tools/check.go
- tools/go.mod
- tools/old.go
- tools/tools.go
> Use Go 1.20

- .codecov.yml
- .github/workflows/js.yml
- .gitignore
- Taskfile.yml
- cmd/ferretdb/main_test.go
- integration/Taskfile.yml
- integration/setup/listener.go
- integration/setup/setup.go
- internal/wire/wire_test.go
> Small cleanups

- .github/workflows/debug.yml
- .github/workflows/docker.yml
- .github/workflows/docs-preview.yml
- .github/workflows/docs.yml
- Taskfile.yml
See #1589 and comments there.
Closes #1800.
The time we spend on this is not worth it – docs build much faster than integration tests run.
> Remove CI optimization that does not work

- internal/handlers/common/msg_listcommands.go
I stumbled upon this whilst testing Studio 3T.
> Add lowercase variant of `dbstats`

- integration/query_comparison_compat_test.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/pg/pgdb/query_test.go
- internal/handlers/tigris/tigrisdb/query.go
- internal/handlers/tigris/tigrisdb/query_test.go
> Pushdown `bool` values

- website/docs/reference/supported_commands.md
> Update aggregation in supported command document

- internal/handlers/pg/msg_saslstart.go
> Fix `saslStart` for particular clients

- internal/handlers/common/aggregations/stage.go
- website/docs/telemetry.md
Useful for passionate adopters.
> Document explicit telemetry sharing

- internal/handlers/common/aggregations/count.go
- internal/handlers/common/aggregations/group.go
- internal/handlers/common/aggregations/group_count.go
- internal/handlers/common/aggregations/sort.go
- internal/handlers/pg/pgdb/transactions.go
See https://github.com/FerretDB/FerretDB/pull/2151.
> Fix telemetry tag and improve unimplemented error in aggregation

- Taskfile.yml
- build/docker/all-in-one.Dockerfile
- build/docker/development.Dockerfile
- build/docker/production.Dockerfile
> Improve build cache usage

- integration/query_evaluation_compat_test.go
This test should be skipped **for** arm64, not the other way around.
> Skip a `$mod` test for arm64

- README.md
- website/docs/quickstart_guide/docker.md
> Tweak Docker docs a bit

- .github/dependabot.yml
To make it easier to track those PRs.
> Tweak dependabot config

- internal/clientconn/conninfo/conn_info.go
- internal/handlers/common/filter.go
- internal/handlers/common/filter_iterator.go
- internal/handlers/pg/msg_aggregate.go
- internal/handlers/pg/msg_find.go
- internal/handlers/pg/pgdb/query.go
- internal/handlers/pg/pgdb/query_iterator.go
- internal/handlers/tigris/msg_aggregate.go
- internal/handlers/tigris/msg_find.go
- internal/handlers/tigris/tigrisdb/query.go
- internal/handlers/tigris/tigrisdb/query_iterator.go
- internal/types/document.go
- internal/types/document_iterator_test.go
- internal/types/documents_iterator.go
> Filter documents with iterators

- internal/clientconn/conn.go
- internal/clientconn/conninfo/conn_info.go
- internal/clientconn/conninfo/cursor.go
- internal/clientconn/listener.go
- internal/handlers/common/aggregations/group.go
- internal/handlers/pg/pgdb/collections.go
- internal/handlers/pg/pgdb/query_iterator.go
- internal/handlers/pg/pgdb/query_test.go
- internal/handlers/pg/pgdb/transactions.go
- internal/handlers/tigris/tigrisdb/query_iterator.go
- internal/handlers/tigris/tigrisdb/query_test.go
- internal/types/array_iterator.go
- internal/types/document_iterator.go
- internal/util/iterator/iterator_test.go
- internal/util/iterator/slice.go
- internal/util/iterator/values.go
- internal/util/resource/resource.go
- internal/util/telemetry/reporter.go
> Improve resource tracking

- .github/ISSUE_TEMPLATE/bug.yml
- CONTRIBUTING.md
> Document test script

- .github/workflows/debug.yml
- .github/workflows/packages.yml
Closes #2368.
Refs actions/checkout#290.
> Fix version.txt generation for git tags

- .github/workflows/docs-preview.yml
- website/docs/reference/supported-commands.md
Refs FerretDB/github-actions#160.
> Add comments to our documentation workflow

- website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
> Fix YAML indentation

- cmd/envtool/envtool.go
- integration/commands_administration_test.go
- internal/clientconn/listener.go
- internal/handlers/pg/pgdb/transactions.go
- internal/handlers/tigris/tigrisdb/databases.go
- internal/util/ctxutil/ctxutil.go
- internal/util/ctxutil/ctxutil_test.go
> Minor cleanup of exponential backoff with jitter

- internal/handlers/pg/pgdb/pool.go
Refs cockroachdb/cockroach#101715.
> Add workaround for CockroachDB issue

- integration/query_projection_compat_test.go
- internal/handlers/common/projection.go
> Return unsupported operator error for `$` projection operator

- integration/commands_diagnostic_test.go
> Remove version and name assertions in integration tests

- internal/util/iterator/count.go
- internal/util/iterator/func.go
- internal/util/iterator/iterator.go
- internal/util/iterator/iterator_test.go
- internal/util/iterator/values.go
- internal/util/iterator/with_close.go
They will be used in future PRs.
> Add helpers for iterators and generators

- integration/query_projection_compat_test.go
- internal/handlers/common/projection.go
> Fix empty projections panic

- .github/workflows/format.yml
- Taskfile.yml
- build/deps/ferretdb-prettier.Dockerfile
- build/deps/prettier.Dockerfile
- docker-compose.yml
It can be used without permission problems.
> Use our own Prettier Docker image

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/chore.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/PROCESS.md
- .github/workflows/go.yml
- .github/workflows/integration-trust.yml
- .github/workflows/integration.yml
- CONTRIBUTING.md
See it in action: https://github.com/AlekSi/FerretDB/issues/new/choose
> Tweak issue templates and contributing docs

- website/docs/quickstart-guide/rpm.md
> Fix typo on RPM package file name

- website/docs/reference/supported-commands.md
Make aggregation pipelines visible by default.
> Update documentation formatting

- internal/backends/backend.go
- internal/backends/database.go
- internal/backends/error.go
- internal/backends/errorcode_string.go
- internal/backends/sqlite/backend.go
- internal/backends/sqlite/collection.go
- internal/backends/sqlite/database.go
- internal/handlers/hana/cmd_query.go
- internal/handlers/pg/msg_hello.go
- internal/handlers/pg/msg_ismaster.go
- internal/handlers/sqlite/cmd_query.go
- internal/handlers/sqlite/msg_create.go
- internal/handlers/sqlite/msg_drop.go
- internal/handlers/sqlite/msg_dropdatabase.go
- internal/handlers/sqlite/msg_hello.go
- internal/handlers/sqlite/msg_ismaster.go
- internal/handlers/sqlite/msg_listcollections.go
- internal/handlers/sqlite/msg_listdatabases.go
- internal/handlers/sqlite/msg_ping.go
- internal/handlers/tigris/cmd_query.go
- internal/handlers/tigris/msg_hello.go
- internal/handlers/tigris/msg_ismaster.go
* `create`
* `drop`
* `dropDatabase`
* `hello`
* `isMaster`
* `listCollections`
* `listDatabases`
* `ping`
Closes #2387.
> Implement some SQLite backend commands

- internal/backends/backend.go
- internal/backends/collection.go
- internal/backends/database.go
- internal/backends/doc.go
- internal/backends/sqlite/backend.go
- internal/backends/sqlite/database.go
- internal/clientconn/conninfo/conn_info.go
- internal/clientconn/cursor/cursor.go
- internal/handlers/pg/pgdb/query_iterator.go
- internal/handlers/sqlite/msg_create.go
- internal/handlers/sqlite/msg_drop.go
- internal/handlers/sqlite/msg_dropdatabase.go
- internal/handlers/sqlite/msg_listcollections.go
- internal/handlers/tigris/tigrisdb/query_iterator.go
- internal/types/array_iterator.go
- internal/types/document_iterator.go
- internal/util/iterator/func.go
- internal/util/iterator/slice.go
- internal/util/observability/funccall.go
- internal/util/observability/observability.go
> Add basic observability into backend interfaces

- internal/backends/collection.go
- internal/backends/sqlite/collection.go
- internal/backends/sqlite/database.go
- internal/backends/sqlite/metadata_storage.go
- internal/backends/sqlite/pool.go
- internal/backends/sqlite/query_iterator.go
- internal/handlers/sqlite/msg_find.go
> Implement query request for SQLite backend 

- .github/workflows/integration.yml
- .gitignore
- Taskfile.yml
- integration/Taskfile.yml
- integration/query_projection_compat_test.go
- integration/setup/listener.go
- integration/setup/setup.go
- integration/shareddata/composites.go
- integration/shareddata/provider.go
- integration/shareddata/scalars.go
- internal/backends/collection.go
- internal/backends/sqlite/collection.go
- internal/backends/sqlite/database.go
- internal/handlers/hana/msg_setfreemonitoring.go
- internal/handlers/registry/sqlite.go
- internal/handlers/sqlite/msg_getfreemonitoringstatus.go
- internal/handlers/sqlite/msg_insert.go
- internal/handlers/sqlite/msg_setfreemonitoring.go
- internal/handlers/sqlite/sqlite.go
They fail for now, but at least they start!
> Run integration tests for `sqlite` handler

- cmd/envtool/envtool.go
- cmd/envtool/envtool_test.go
- integration/commands_diagnostic_test.go
- integration/setup/listener.go
- internal/backends/sqlite/backend.go
- internal/backends/sqlite/metadata_storage.go
- internal/handlers/registry/sqlite.go
- internal/handlers/sqlite/msg_find.go
- internal/handlers/sqlite/msg_serverstatus.go
- internal/handlers/sqlite/sqlite.go
- internal/util/ctxutil/ctxutil_test.go
That allows more tests to run on CI.
> Create SQLite directory if needed

- website/blog/2023-05-22-ferretdb-v-1-2-0-minor-release.md
- website/static/img/blog/ferretdb-1-2-0-minor-release.jpg
> Add release blog post for FerretDB version 1.2.0

- .github/workflows/packages.yml
- integration/distinct_compat_test.go
- integration/distinct_test.go
- internal/handlers/commonparams/extract_params.go
- internal/handlers/commonparams/extract_params_test.go
> Add `distinct` command errors test

- cmd/envtool/envtool.go
- cmd/envtool/envtool_test.go
> Implement `envtool version` command

- integration/main_test.go
> Make `go test -list=.` work

- integration/indexes_compat_test.go
> Call `ListSpecifications` driver's method in tests to check indexes

- internal/handlers/common/count_iterator.go
- internal/util/iterator/iterator.go
> Simplify `CountIterator`

- internal/handlers/pg/pgdb/query_iterator.go
- internal/handlers/tigris/tigrisdb/query_iterator.go
- internal/util/iterator/count.go
- internal/util/iterator/func.go
- internal/util/iterator/values.go
> Check for `nil` values in iterators explicitly

- cmd/ferretdb/main.go
- integration/setup/startup.go
> Trigger GC to run finalizers

- integration/findandmodify_compat_test.go
> Fix `findAndModify` tests for MongoDB 6.0.6

- .github/RELEASE_CHECKLIST.md
- CHANGELOG.md
> Prepare v1.3.0 release

- website/blog/2023-05-22-ferretdb-v-1-2-0-minor-release.md
- website/blog/2023-06-05-ferretdb-new-release-v-1-3-0.md
- website/blog/2023-06-05-ferretdb-v-1-3-0-new-release.md
- website/static/img/blog/ferretdb-v1.3.0.jpg
> Add blog post for FerretDB v1.3.0

- website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
https://blog.ferretdb.io/tags/release/ – 1.0.0 is not there.
> Add `release` tag to release blog post

- build/deps/ferretdb-wrangler.Dockerfile
- build/docker/all-in-one.Dockerfile
- build/docker/development.Dockerfile
- build/docker/production.Dockerfile
> Bump Go to 1.20.5

- integration/aggregate_documents_test.go
- integration/basic_test.go
- integration/commands_administration_test.go
- integration/commands_diagnostic_test.go
- integration/commands_freemonitoring_test.go
- integration/create_test.go
- integration/delete_test.go
- integration/distinct_test.go
- integration/findandmodify_test.go
- integration/helpers.go
- integration/indexes_compat_test.go
- integration/indexes_test.go
- integration/insert_command_compat_test.go
- integration/insert_command_test.go
- integration/query_array_test.go
- integration/query_bitwise_test.go
- integration/query_evaluation_test.go
- integration/query_projection_test.go
- integration/query_test.go
- integration/update_field_test.go
> Check error message in non compat integration tests

- CONTRIBUTING.md
- integration/commands_freemonitoring_test.go
- integration/indexes_compat_test.go
Closes FerretDB/engineering#66.
It's a part of the main issue, based on the outcome of #2816. 
This PR only describes the current guidelines. The new guidelines will be added in separate PRs together with the changes to meet these new guidelines.
> Describe current test naming conventions in the contributing guidelines

- integration/helpers.go
- integration/query_test.go
> Add tests for `find`/`getMore` `batchSize`

- .github/workflows/go-trust.yml
- .github/workflows/go.yml
- integration/setup/startup.go
Compare and contrast:
* https://github.com/FerretDB/FerretDB/actions/runs/5319477939/jobs/9632025880
* https://github.com/FerretDB/FerretDB/actions/runs/5319477939/jobs/9632688869
> Make it easier to debug GitHub Actions

- website/blog/2023-06-21-meet-ferretdb-percona-university-casablanca-belgrade.md
- website/static/img/blog/percona-university.jpg
> Add blog post on "Meet FerretDB at Percona University in Casablanca and Belgrade"

- CONTRIBUTING.md
Fix the incorrect sequence of steps.
> Tweak contributing guidelines

- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/listener.go
- integration/setup/setup.go
- internal/clientconn/listener.go
- internal/handlers/handlers.go
- internal/util/resource/resource.go
- internal/util/testutil/testutil.go
This PR uncovers a problem with resource tracking that the next PR will fix.
> Fix cancelation signals propagation

- website/blog/2023-06-26-configure-ferretdb-work-percona-distribution-postgresql.md
- website/static/img/blog/displaying-studio3t-data.png
- website/static/img/blog/ferretdb-percona-postgres.jpg
- website/static/img/blog/percona-ferretdb.png
- website/static/img/blog/postgresql.png
> Add blog post on "How to Configure FerretDB to work on Percona Distribution for PostgreSQL"

- integration/basic_test.go
Removed the test as it tests driver and not the database.
> Fix integration tests after bumping deps

- internal/handlers/common/common.go
> Set `minWireVersion` to 0

- README.md
- build/docker/all-in-one.Dockerfile
- website/docs/quickstart-guide/go.md
- website/docs/quickstart-guide/macos.md
> Mention SQLite in README.md

- .golangci-new.yml
- .golangci.yml
- integration/.golangci-new.yml
- integration/.golangci.yml
- integration/helpers.go
- integration/setup/client.go
- integration/setup/listener.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/setup/test_helpers.go
- internal/bson/bson_test.go
- internal/handlers/pg/pgdb/pgdb_test.go
- internal/handlers/sjson/sjson_test.go
- internal/handlers/tigris/tjson/tjson_test.go
- internal/util/testutil/db.go
- internal/util/testutil/dump.go
- internal/util/testutil/equal.go
- internal/util/testutil/hexdump.go
- internal/util/testutil/path.go
- internal/util/testutil/pg.go
- internal/util/testutil/testutil.go
- internal/util/testutil/xfail.go
- internal/wire/wire_test.go
It will be used by the next PR.
> Make a copy of the `testing.TB` interface

- internal/handlers/commoncommands/msg_buildinfo.go
- internal/handlers/commoncommands/msg_currentop.go
- internal/handlers/commoncommands/msg_debugerror.go
- internal/handlers/commoncommands/msg_getcmdlineopts.go
- internal/handlers/commoncommands/msg_hostinfo.go
- internal/handlers/commoncommands/msg_listcommands.go
- internal/handlers/commoncommands/msg_logout.go
- internal/handlers/commoncommands/msg_whatsmyuri.go
- internal/handlers/hana/msg_logout.go
- internal/handlers/pg/msg_logout.go
- internal/handlers/sqlite/msg_logout.go
> Move `logout` to `commoncommands`

- CHANGELOG.md
> Prepare v1.6.0 release

- website/blog/2023-07-17-ferretdb-v-1-6-0.md
- website/static/img/blog/ferretdb-v1.6.0.jpg
> Add blog post for FerretDB v1.6.0

- website/blog/2023-07-19-community-matters-fireside-chat-cockroachdb.md
> Update Blog Post

- website/docs/contributing/writing-guide.md
> Update tags formatting in writing guide

- .gitattributes
- website/blog/2023-07-20-using-ferretdb-mingo.md
- website/blog/2023-07-24-using-mingo-analyze-visualize-ferretdb-data.md
- website/static/img/blog/ferretdb-mingo.jpg
- website/static/img/blog/ferretdb-mingo/aggregation-operations.gif
- website/static/img/blog/ferretdb-mingo/basic-query.png
- website/static/img/blog/ferretdb-mingo/collection-data.png
- website/static/img/blog/ferretdb-mingo/connection-url-ferretdb.png
- website/static/img/blog/ferretdb-mingo/connection-window.png
- website/static/img/blog/ferretdb-mingo/mingo-dashboard.png
- website/static/img/blog/ferretdb-mingo/timerange-query.gif
> Add blog post on "Using Mingo with FerretDB"

- .github/PROCESS.md
Please read and share your feedback. This is an expectation we have but it doesn't seem to be really visible.
> Add daily progress principle to `PROCESS.md`

- internal/handlers/pg/msg_explain.go
- internal/handlers/pg/msg_find.go
> Fix pushdown for `find` with `filter` and `limit`

- website/blog/2023-03-21-mongodb-vs-postgresql-database-comparison.md
> Update MongoDB comparision blog post

- .gitignore
- internal/backends/sqlite/metadata/pool/pool_test.go
- internal/backends/sqlite/metadata/pool/uri.go
- internal/backends/sqlite/metadata/pool/uri_test.go
- internal/handlers/pg/pgdb/pool.go
- website/docs/configuration/flags.md
- website/docs/understanding-ferretdb.md
> Tweak and document SQLite URI parameters

- integration/aggregate_documents_compat_test.go
- integration/insert_compat_test.go
- internal/handlers/sqlite/msg_aggregate.go
- internal/util/testutil/testfail/expected_test.go
> Expect some `aggregate` and `insert` tests to fail for SQLite

- integration/commands_administration_compat_test.go
- integration/commands_administration_test.go
- integration/commands_authentication_test.go
- integration/commands_diagnostic_test.go
- `commands_administration_compat_test.go`
- `commands_administration_test.go`
- `commands_authentication_test.go`
- `commands_diagnostic_test.go`
Closes #3131.
> Make administration command integration tests pass for SQLite

- integration/indexes_compat_test.go
> Make index integration tests pass for SQLite

- integration/aggregate_documents_compat_test.go
- integration/aggregate_variables_compat_test.go
Closes #1992.
This PR is the analysis of the task to add tests where expression would be used.
> Add tests for `$$ROOT` aggregation expression variable

- integration/findandmodify_compat_test.go
- internal/handlers/common/findandmodify.go
> Do not return immutable `_id` error from `findAndModify` for upserting same `_id`

- website/blog/2023-08-14-ferretdb-new-release-v180.md
- website/static/img/blog/ferretdb-v1.8.0.jpg
> Add blog post for FerretDB v1.8.0

- website/docs/basic-operations/read.md
- website/docs/reference/glossary.md
**Motivation:**
Improving FerretDB documentation.
**Changes:**
Adding typo correction in the documentation.
1) reference (glossary.md)
Current: processsing , New change: processing
2) basic-operation (read.md)
Current: retrieveing, New change: retrieving
> Fix typos in documentation

- website/docs/contributing/writing-guide.md
It will be hidden in the sidebar but available by direct URL.
> Make the writing guide accessible but unlisted

- cmd/ferretdb/main.go
- internal/backends/database.go
- internal/backends/sqlite/database.go
- internal/backends/sqlite/metadata/registry.go
> Add stubs for `renameCollection`

- integration/explain_compat_test.go
> Update issue links

- .github/settings.yml
- Taskfile.yml
- internal/backends/collection.go
- internal/backends/sqlite/collection.go
- internal/handlers/sjson/sjson_test.go
- internal/handlers/sqlite/msg_explain.go
> Add stubs for `explain`

- integration/commands_diagnostic_test.go
- integration/distinct_test.go
- integration/query_test.go
- internal/clientconn/cursor/cursor_test.go
- internal/handlers/common/find.go
- internal/handlers/commonerrors/command.go
- internal/handlers/commonerrors/commonerrors_test.go
- internal/handlers/commonerrors/error.go
- internal/handlers/commonerrors/write.go
- internal/handlers/commonerrors/write_error.go
- internal/handlers/pg/msg_insert.go
- internal/handlers/pg/msg_update.go
- internal/util/iterator/testiterator/testiterator_test.go
- internal/util/observability/observability_test.go
- internal/util/resource/resource_test.go
- internal/util/testutil/teststress/stress_test.go
- internal/util/testutil/testtb/tb_test.go
- website/blog/2023-08-18-ferretdb-going-postgres-ibiza-2023.md
- website/static/img/blog/postgres-ibiza-2023.jpg
Do not allow error unwrapping.
More to come.
> Simplify `commonerrors` package

- .github/workflows/packages.yml
https://quay.io/organization/ferretdb
Closes #2229.
> Publish Docker images on quay.io

- integration/aggregate_variables_compat_test.go
Closes #1992.
It adds tests, the issue should remain open.
> Add tests for accessing aggregation variable `$$ROOT` field

- integration/commands_administration_compat_test.go
- integration/commands_administration_test.go
- integration/commands_diagnostic_test.go
- internal/handlers/sqlite/msg_serverstatus.go
> Update TODO comments

- internal/backends/database.go
- internal/backends/postgresql/database.go
- internal/backends/sqlite/database.go
- internal/handlers/sqlite/msg_dbstats.go
Closes #3259.
This PR is about backend interface used by `dbStats`. Implementation will be done in another PR.
> Add backend interface for `dbStats`

- internal/types/document_validation_test.go
> Add tests for validation bug

- internal/backends/collection.go
- internal/backends/doc.go
- internal/backends/postgresql/collection.go
- internal/backends/sqlite/collection.go
- internal/handlers/sqlite/msg_collmod.go
- internal/handlers/sqlite/msg_datasize.go
- internal/handlers/sqlite/msg_delete.go
- internal/handlers/sqlite/msg_dropindexes.go
- internal/handlers/sqlite/msg_findandmodify.go
- internal/handlers/sqlite/msg_listindexes.go
- internal/handlers/sqlite/msg_renamecollection.go
- internal/handlers/sqlite/sqlite.go
- internal/types/array.go
- internal/types/document.go
> Expand architecture docs, add comments

- integration/helpers.go
- internal/backends/collection.go
- internal/backends/sqlite/collection.go
- internal/handlers/common/filter.go
- internal/handlers/sqlite/msg_delete.go
- internal/types/array.go
- internal/types/array_test.go
- internal/types/document.go
- internal/types/document_test.go
- website/docs/quickstart-guide/rpm.md
> Make `delete`s atomic for SQLite

- internal/backends/sqlite/database.go
- internal/backends/sqlite/metadata/registry.go
- internal/backends/sqlite/metadata/registry_test.go
> Make registry return full collection info

- internal/backends/collection.go
- internal/backends/database.go
- internal/backends/postgresql/collection.go
- internal/backends/postgresql/database.go
- internal/backends/sqlite/collection.go
- internal/backends/sqlite/database.go
- internal/backends/sqlite/database_test.go
- internal/handlers/sqlite/msg_dbstats.go
Closes #3259.
This PR is about interface, implementation will follow in next PR.
> Add backend interface for `collStats`

- .github/workflows/js.yml
- Taskfile.yml
- cmd/envtool/envtool.go
- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- internal/backends/postgresql/metadata/metadata.go
- internal/backends/postgresql/metadata/uri.go
- internal/backends/sqlite/metadata/metadata.go
- internal/backends/sqlite/metadata/pool/pool.go
- internal/handlers/common/setfreemonitoring.go
- internal/handlers/pg/pgdb/pgdb_test.go
- internal/handlers/pg/pgdb/pool.go
- internal/util/debugbuild/debugbuild.go
- internal/util/debugbuild/debugbuild_on.go
That makes it easier to use FerretDB with another proxy or other backends. See https://github.com/FerretDB/FerretDB/issues/3252#issuecomment-1697912957.
> Do not change `search_path` parameter

- integration/commands_administration_test.go
- internal/backends/backend.go
- internal/backends/postgresql/backend.go
- internal/backends/sqlite/backend.go
- internal/handlers/commonparams/params.go
- internal/handlers/pg/msg_datasize.go
- internal/handlers/pg/msg_renamecollection.go
- internal/handlers/sqlite/msg_datasize.go
- internal/handlers/sqlite/msg_serverstatus.go
> Implement `serverStatus` and `dataSize` commands for SQLite

- website/docs/contributing/writing-guide.md
> Update the writing guide

- integration/update_field_compat_test.go
- internal/handlers/common/update.go
- website/docs/reference/supported-commands.md
> Cleanup `$bit` update operator

- website/blog/2021-11-05-mangodb-overwhelming-enthusiasm-for-truly-open-source-mongodb-replacement.md
- website/blog/2021-12-01-mangodb-has-a-new-name-and-the-momentum-is-stronger-than-ever-meet-ferretdb.md
- website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
- website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
- website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
- website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
- website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
- website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
- website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
- website/blog/2022-08-23-open-source-is-in-danger.md
- website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
- website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
- website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
- website/blog/2022-11-11-new-release-ferretdb-0-6-1.md
- website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
- website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
- website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
- website/blog/2022-12-23-ferretdb-new-release-with-tls.md
- website/blog/2023-01-04-ferretdb-beta-version-authentication.md
- website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
- website/blog/2023-01-31-ferretdb-v-0-9-0-developer-preview.md
- website/blog/2023-02-07-5-database-alternatives-mongodb-2023.md
- website/blog/authors.yml
> Update blog authors

- integration/indexes_command_compat_test.go
- internal/handlers/sqlite/msg_dropindexes.go
> Fix params handling for `dropIndexes` implementation for SQLite

- Taskfile.yml
- build/docker/all-in-one.Dockerfile
- build/docker/development.Dockerfile
- build/docker/production.Dockerfile
> Build Docker images for `arm/v6`

- integration/insert_command_test.go
- integration/update_field_test.go
> Add test for inserting different data types

- website/blog/2023-01-04-ferretdb-beta-version-authentication.md
> Improve blog format

- integration/setup/listener.go
> Recreate test directory

- integration/Taskfile.yml
- integration/benchmarks_test.go
- integration/setup/setup.go
- integration/setup/startup.go
- integration/shareddata/benchmark_provider.go
> Use filter and insert more documents in `BenchmarkReplaceSettingsDocument`

- internal/handlers/common/saslstart_plain_test.go
- internal/handlers/commonpath/commonpath_test.go
- internal/types/array.go
- internal/types/array_test.go
- internal/types/compare.go
- internal/types/compare_order.go
- internal/types/document.go
- internal/types/document_test.go
- internal/types/document_validation.go
- internal/types/document_validation_test.go
- internal/types/format.go
- internal/types/identical.go
- internal/types/path.go
- internal/types/path_test.go
- internal/types/types.go
- internal/util/testutil/equal.go
- internal/util/testutil/path.go
Check that passed values have valid types. Fix invalid tests.
> Enforce valid `types` usage

- internal/backends/postgresql/backend.go
- internal/backends/postgresql/collection.go
- internal/backends/postgresql/database.go
- internal/backends/postgresql/metadata/metadata.go
- internal/backends/postgresql/metadata/registry.go
> Add `TODO`s

- internal/backends/postgresql/database.go
- internal/backends/postgresql/metadata/pool/pool.go
- internal/backends/sqlite/database.go
- internal/backends/sqlite/metadata/pool/pool.go
To trigger issues similar to #3409 earlier.
Closes #3393.
> Implement `RenameCollection`

- cmd/ferretdb/main.go
- internal/bson/bson.go
- internal/bson/document.go
- internal/bson/document_test.go
- internal/handlers/common/filter.go
- internal/handlers/common/positional_operator.go
- internal/handlers/common/projection.go
- internal/util/debug/debug.go
- internal/wire/op_query.go
- internal/wire/op_reply.go
> Remove extra function

- .github/workflows/packages.yml
- Taskfile.yml
- build/docker/development.Dockerfile
- build/docker/production.Dockerfile
Export fewer files from Docker.
> Add a workaround for Docker build failures

- internal/backends/postgresql/metadata/registry.go
- internal/backends/sqlite/metadata/metadata.go
- internal/backends/sqlite/metadata/registry.go
- internal/backends/validation.go
Just a small clean-up before we use it in more places.
> Extract `ReservedPrefix` constant

- website/blog/2023-09-29-ferretdb-database-choice-enmeshed-customers.md
> Fix blog post formatting

- integration/setup/client.go
- internal/backends/collection.go
- internal/backends/database.go
- internal/backends/postgresql/postgresql.go
- internal/backends/sqlite/sqlite.go
> Use `Ping` for checking connection

- .github/settings.yml
- README.md
https://github.com/AlekSi/FerretDB/blob/mermaid/README.md
> Add mermaid diagrams

- internal/backends/postgresql/metadata/registry_test.go
- internal/backends/postgresql/postgresql.go
> Fix unit tests for indexes

- internal/backends/collection_test.go
- internal/backends/postgresql/database_test.go
- internal/backends/postgresql/postgresql.go
> Add info about indexes to `dbStats` response

- website/blog/2023-10-11-ferretdb-v112-available.md
- website/blog/2023-10-11-ferretdb-v1120-available.md
- website/static/img/blog/ferretdb-v1.12.png
> Add release blog post for FerretDB v1.12

- Taskfile.yml
- cmd/envtool/envtool.go
- internal/backends/collection.go
- internal/backends/postgresql/query.go
- internal/handlers/common/delete_params.go
- internal/handlers/common/update_params.go
- internal/handlers/pg/msg_delete.go
- internal/handlers/sqlite/msg_find.go
They are not compatible with the new PostgreSQL backend.
> Do not create databases during local setup

- integration/insert_command_test.go
Add integration tests for error cases
Closes #2804.
> Add tests for insertion of documents with invalid `_id` fields

- .golangci.yml
- integration/.golangci.yml
- integration/setup/setup.go
- integration/setup/startup.go
- internal/backends/backend.go
- internal/backends/collection_test.go
- internal/backends/database.go
- internal/backends/error.go
- internal/backends/postgresql/metadata/indexes.go
- internal/backends/postgresql/metadata/pool/opendb.go
- internal/backends/postgresql/metadata/registry_test.go
- internal/backends/sqlite/metadata/registry.go
- internal/backends/sqlite/metadata/settings.go
- internal/handlers/common/aggregations/stages/projection/projection.go
- internal/handlers/common/filter.go
- internal/handlers/common/projection.go
- internal/handlers/common/update.go
- internal/handlers/commonparams/extract_params.go
- internal/handlers/pg/msg_renamecollection.go
- internal/handlers/pg/pgdb/collections.go
- internal/handlers/sqlite/msg_aggregate.go
- internal/handlers/sqlite/msg_collstats.go
- internal/handlers/sqlite/msg_createindexes.go
- internal/types/document.go
- internal/types/path.go
- internal/util/testutil/equal.go
> Use stdlib's `slices` package

- internal/handlers/pg/msg_aggregate.go
> Remove done TODO

- Taskfile.yml
- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/listener.go
- internal/handlers/pg/msg_getlog.go
- internal/handlers/registry/postgresql.go
- internal/handlers/registry/registry.go
Add `task run-old` and some logging.
> Make it easier to run old PG handler

- integration/query_array_compat_test.go
- integration/query_comparison_compat_test.go
- integration/query_compat_test.go
- integration/query_projection_compat_test.go
> Unskip filter pushdown integration tests

- website/blog/2023-10-18-build-internal-apps-illa-cloud-ferretdb.md
- website/static/img/blog/ferretdb-illacloud.jpg
> Update ILLA blog post

- Taskfile.yml
Fixes things like tests panicking after commit, etc.
> Keep envtool's version always up-to-date

- .github/workflows/docs.yml
- .github/workflows/website-preview.yml
- .golangci.yml
- Taskfile.yml
- integration/.golangci.yml
- internal/backends/helpers_test.go
- internal/backends/postgresql/collection.go
- internal/backends/sqlite/collection.go
- internal/backends/sqlite/database_test.go
- internal/backends/sqlite/metadata/pool/opendb.go
- internal/backends/sqlite/metadata/pool/pool.go
- internal/backends/sqlite/metadata/pool/pool_test.go
- internal/backends/sqlite/metadata/pool/uri.go
- internal/backends/sqlite/metadata/pool/uri_test.go
- internal/backends/sqlite/metadata/registry_test.go
- internal/backends/sqlite/sqlite_test.go
- internal/handlers/pg/msg_update.go
- website/docs/configuration/flags.md
This PR prevents loading of database files from disk when in-memory URL is used.
Plus a few smaller fixes.
Closes #3409.
> Fix some tests for SQLite backend

- internal/backends/decorators/oplog/backend.go
- internal/backends/decorators/oplog/collection.go
- internal/backends/decorators/oplog/database.go
- internal/backends/decorators/oplog/oplog.go
It should be created manually.
> Do not create OpLog database/collection on a fly

- website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
> Add Links to blog

- integration/aggregate_documents_compat_test.go
- internal/backends/postgresql/collection.go
- internal/handlers/sqlite/msg_aggregate.go
- internal/handlers/sqlite/msg_explain.go
> Implement pushdown for `aggregate`

- CHANGELOG.md
- build/trivy-secret.yml
- tools/go.mod
- tools/go.sum
- website/docs/configuration/flags.md
> Prepare v1.13.0 release

- integration/create_test.go
- internal/backends/database.go
- internal/backends/postgresql/metadata/metadata.go
- internal/backends/postgresql/metadata/registry.go
- internal/backends/sqlite/metadata/registry.go
- internal/handlers/sqlite/msg_create.go
> Disallow capped collection creation when disabled

- website/blog/2023-10-24-ferretdb-v1130-new-postgresql-backend.md
- website/static/img/blog/ferretdb-v1.13.0.png
> Add blogpost for Ferretdb v1.13.0

- build/docker/all-in-one.Dockerfile
- build/docker/development.Dockerfile
- build/docker/production.Dockerfile
- build/nfpm.yml
- cmd/envtool/tests.go
- cmd/envtool/tests_test.go
- tools/go.mod
- tools/go.sum
Highlight the problem with parallel tests and setup.
> Add timing information to `envtool` output

- website/blog/2023-11-07-ferretdb-releases-v1140.md
- website/static/img/blog/ferretdb-v1.14.0.jpg
> Add release blogpost for FerretDB v.1.14.0

- website/blog/2023-10-30-building-mongodb-like-developer-experience-vultr.md
> Fix content error

- .github/settings.yml
- Taskfile.yml
- internal/backends/decorators/dummy/backend.go
- internal/backends/decorators/dummy/collection.go
- internal/backends/decorators/dummy/database.go
- internal/backends/decorators/oplog/backend.go
- internal/backends/decorators/oplog/collection.go
- internal/backends/decorators/oplog/database.go
- internal/backends/hana/backend.go
- internal/backends/postgresql/backend.go
- internal/backends/sqlite/backend.go
> Small assorted tweaks

- website/blog/2023-11-20-ferretdb-releases-v1150.md
- website/static/img/blog/ferretdb-v1.15.0.jpg
> Add blogpost for release v.1.15

- internal/backends/collection.go
- internal/backends/postgresql/query_iterator.go
- internal/backends/sqlite/query_iterator.go
- internal/handlers/sqlite/msg_explain.go
- internal/handlers/sqlite/msg_find.go
- internal/types/document.go
- internal/types/timestamp.go
- internal/types/timestamp_test.go
> Make RecordID a signed value

- .github/workflows/_integration.yml
- .github/workflows/go-extra.yml
- Taskfile.yml
Don't run it for each PR yet, but run it for the `main` branch.
> Add MySQL backend to CI

- build/mongodb.conf
- internal/backends/collection.go
> Add TODOs about pushdowns

- .golangci.yml
- internal/backends/postgresql/query_iterator.go
- internal/backends/sqlite/query_iterator.go
- internal/clientconn/cursor/cursor.go
- internal/clientconn/cursor/registry.go
- internal/handler/common/aggregations/stages/unwind.go
- internal/handler/common/sort_iterator.go
- internal/handler/msg_aggregate.go
- internal/handler/msg_find.go
- internal/handler/msg_getmore.go
- internal/util/resource/resource.go
> Log batches for `find`, `aggregate`, `getMore`

- Taskfile.yml
- cmd/envtool/tests_test.go
- integration/aggregate_documents_test.go
- integration/commands_administration_test.go
- integration/cursors/cursors.go
- integration/cursors/getmore_test.go
- integration/embedded_test.go
- integration/integration.go
- integration/query_test.go
- integration/setup/helpers.go
- integration/setup/listener.go
- integration/setup/setup.go
- internal/clientconn/listener.go
- internal/handler/registry/registry.go
That's an experiment and does not change our existing naming scheme yet.
> Support subdirectories for integration tests

- website/blog/2023-12-05-new-ferretdb-release-v116.md
- website/static/img/blog/ferretdb-v1.16.0.jpg
> Add new release FerretDB v1.16.0 blog post

- internal/clientconn/cursor/cursor.go
- internal/clientconn/cursor/registry.go
- internal/handler/msg_aggregate.go
- internal/handler/msg_find.go
Extracted to make the next PR smaller.
> Refactor cursor creation

- website/static/img/blog/ferretdb-v1.16.0.jpg
> Change release blogpost image

- website/blog/2023-12-19-ferretdb-releases-v117.md
- website/static/img/blog/ferretdb-v1.17.0.jpg
> Add release blogpost for v1.17.0

- Taskfile.yml
- cmd/envtool/envtool.go
> Fix local MySQL setup

- website/blog/2023-12-18-ferretdb-neon-add-mongodb-compatibility.md
> Update blog links

- integration/users/create_user_test.go
- integration/users/drop_all_users_from_database_test.go
- integration/users/drop_user_test.go
> Use `dropAllUsersFromDatabase` in tests

- .github/workflows/docs.yml
- .github/workflows/packages.yml
- CONTRIBUTING.md
- README.md
- build/.textlintrc
- build/deps/ferretdb-prettier.Dockerfile
- build/deps/ferretdb-textlint.Dockerfile
- website/blog/2023-11-15-how-to-package-and-deploy-ferretdb-with-acorn.md
See https://github.com/orgs/community/discussions/16925, "Update - 14 November 2023" part.
> Small clean-ups

- internal/clientconn/conninfo/conn_info.go
- internal/handler/msg_aggregate.go
- internal/handler/msg_connectionstatus.go
- internal/handler/msg_find.go
- internal/handler/msg_getmore.go
- internal/handler/msg_killcursors.go
We need username in multiple places, but not a password.
> Refactor `ConnInfo` in preparation for new auth

- internal/handler/sjson/sjson_test.go
Since the issue #1273 was closed as not planned, we don't need this TODO anymore.
> Cleanup a closed issue

- internal/handler/msg_createindexes.go
> Ignore `sparse` index parameter for now

- integration/cursors/awaitdata_test.go
- internal/handler/msg_getmore.go
> Fix `awaitData` cursor panic

- internal/backends/mysql/metadata/pool/uri.go
- internal/backends/mysql/metadata/registry_test.go
> Allow Native Passwords for testcase

- website/blog/2024-01-08-new-ferretdb-v118-support-oplog-functionality.md
> Tweak blog post a bit

- website/docs/configuration/oplog-support.md
- website/versioned_docs/version-v1.18/configuration/oplog-support.md
> Add documentation for oplog

- Taskfile.yml
> Fix Taskfile.yml indentation

- integration/setup/helpers.go
- integration/users/create_user_test.go
- integration/users/update_user_test.go
- internal/handler/handlererrors/error.go
- internal/handler/handlererrors/errorcode_string.go
- internal/handler/msg_createuser.go
- internal/handler/msg_updateuser.go
Initial implementation of the updateUser command.
Closes #1496.
> Implement `updateUser` command

- CONTRIBUTING.md
- internal/backends/postgresql/helpers.go
- internal/handler/sjson/schema_test.go
Update Go wiki URLs. Update wording.
> Update contributing documentation

- internal/handler/msg_compact.go
> Use `ListCollection` with a filter

- integration/indexes_compat_test.go
- internal/backends/sqlite/metadata/registry.go
- internal/backends/sqlite/metadata/registry_test.go
> Support creating an index on nested fields for SQLite

- .github/workflows/_integration.yml
- .github/workflows/debug.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/go-trusted.yml
- .github/workflows/go.yml
- .github/workflows/js.yml
- .github/workflows/packages.yml
- .github/workflows/security.yml
- build/version/version.go
We will have `main/v1` relatively soon.
> Prepare CI to having multiple main branches

- .golangci.yml
- CONTRIBUTING.md
- Taskfile.yml
- cmd/envtool/envtool.go
- integration/go.mod
- integration/go.sum
- internal/bson2/slog.go
- internal/util/logging/logging.go
- internal/wire/op_msg.go
- internal/wire/wire_test.go
- tools/checkcomments/checkcomments.go
The implementation could be changed later (to remove extra conversions) without changing the interface.
Please a few assorted tweaks.
> Expose raw documents in the `wire` package

- cmd/ferretdb/main.go
The new authentication solution is not ready yet, but we started talking about it.
> Expose new authentication enabling flag

- website/blog/2024-01-30-new-ferretdb-v119-release.md
> Truncate release blog post

- internal/handler/msg_createuser.go
- internal/handler/msg_usersinfo.go
> Remove SCRAM-SHA-256 implementation TODO links

- .github/RELEASE_CHECKLIST.md
- cmd/ferretdb/main.go
- internal/handler/msg_getlog.go
- internal/util/telemetry/reporter.go
- website/docs/telemetry.md
Move another thing from ferretdb.io to ferretdb.com.
No changes in collected data, etc.
> Update telemetry host

- website/blog/2024-02-20-postgresql-can-it-be-a-database-for-everything.md
> Update correct image link

- internal/handler/common/count.go
- internal/handler/common/delete_params.go
- internal/handler/common/insert.go
> Add ignoring maxTimeMS argument in count, insert, update, delete

- cmd/envtool/tests_test.go
- internal/util/password/scramsha1.go
- internal/util/password/scramsha1_test.go
- internal/util/password/scramsha256.go
- internal/util/password/scramsha256_test.go
Legacy shell is picky about it.
> Use correct salt length

- integration/cursors/awaitdata_test.go
See how it is stuck on CI https://github.com/FerretDB/FerretDB/actions/runs/8075825518/job/22063297445?pr=4075
> Skip stuck tailable cursor test

- website/blog/2024-03-21-new-ferretdb-v121-release.md
- website/static/img/blog/ferretdb-v1.21.0.jpg
> Add blog post for FerretDB v1.21 release

- cmd/ferretdb/main.go
> Add dummy setup flags

- integration/count_command_compat_test.go
- integration/query_command_compat_test.go
- integration/update_compat_test.go
- internal/backends/mysql/mysql.go
- internal/handler/common/aggregations/operators/expr.go
- internal/handler/common/aggregations/stages/group.go
- internal/handler/handler.go
> Fix some comments

- cmd/ferretdb/main.go
- cmd/ferretdb/main_unix.go
- cmd/ferretdb/main_windows.go
- internal/util/state/provider.go
> Improve error message for `state.json`

- internal/bson/array.go
- internal/bson/bson.go
- internal/bson/bson_test.go
- internal/bson/decode.go
- internal/bson/document.go
- internal/bson/logging.go
- internal/bson/logging_test.go
- internal/bson/raw_array.go
- internal/bson/raw_document.go
- internal/bson/tag.go
- internal/bson/tag_string.go
> Port BSON changes

- .github/workflows/_integration.yml
- .github/workflows/go.yml
> Use more shards on CI

- cmd/ferretdb/main.go
- integration/insert_command_test.go
- integration/setup/listener.go
- integration/setup/setup.go
- internal/handler/cmd_query.go
- internal/handler/common/ismaster.go
- internal/handler/handler.go
- internal/handler/msg_buildinfo.go
- internal/handler/msg_hello.go
- internal/handler/msg_ismaster.go
- internal/handler/registry/hana.go
- internal/handler/registry/mysql.go
- internal/handler/registry/postgresql.go
- internal/handler/registry/registry.go
- internal/handler/registry/sqlite.go
- internal/types/types.go
> Make maximum document size configurable

- .github/workflows/_integration.yml
- .github/workflows/go.yml
> Revert codecov version fix

- website/docs/migration/migrating-from-mongodb.md
- website/versioned_docs/version-v1.19/migration/migrating-from-mongodb.md
- website/versioned_docs/version-v1.20/migration/migrating-from-mongodb.md
- website/versioned_docs/version-v1.21/migration/migrating-from-mongodb.md
> Fix typo in migration guide

- internal/wire/msg_body.go
- internal/wire/op_msg.go
- internal/wire/op_query.go
- internal/wire/op_reply.go
- internal/wire/wire_test.go
> Port `wire` package changes

- .golangci.yml
- internal/backends/user.go
- internal/handler/handler.go
- internal/handler/msg_createuser.go
- internal/handler/msg_updateuser.go
- internal/handler/users/createuser.go
- internal/handler/users/users.go
- internal/util/password/password.go
- internal/util/password/scram.go
- internal/util/password/scramsha1.go
- internal/util/password/scramsha1_test.go
- internal/util/password/scramsha256.go
- internal/util/password/scramsha256_test.go
> Port `password` changes

- build/ferretdb/all-in-one.Dockerfile
- build/ferretdb/development.Dockerfile
- build/ferretdb/production.Dockerfile
> Replace deprecated syntax in Dockerfiles

- website/blog/2024-06-27-new-ferretdb-v122-user-setup-feature.md
- website/static/img/blog/ferretdb-v1.22.0.jpg
> Add release blog post for FerretDB v.1.22.0

- .golangci.yml
- integration/.golangci.yml
- integration/shareddata/benchmark_provider.go
- integration/shareddata/provider.go
- internal/bson/array.go
- internal/bson/document.go
- internal/bson/raw_array.go
- internal/bson/raw_document.go
- internal/clientconn/connmetrics/conn_metrics.go
- internal/clientconn/connmetrics/listener_metrics.go
- internal/clientconn/cursor/registry.go
- internal/clientconn/listener.go
- internal/handler/handler.go
- internal/util/state/metrics.go
- internal/wire/op_msg.go
- internal/wire/op_query.go
- internal/wire/op_reply.go
> Update comments about interfaces

- integration/diff_08_names_test.go
- integration/setup/client.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/setup/startup.go
> Disable OTEL in tests where collection name might have non-UTF-8 symbols

- integration/commands_authentication_test.go
- integration/integration.go
- integration/setup/setup.go
- integration/users/connection_test.go
- internal/backends/mysql/metadata/registry.go
- internal/backends/postgresql/metadata/registry.go
- internal/clientconn/conninfo/conn_info.go
- internal/handler/commands.go
- internal/handler/msg_connectionstatus.go
- internal/handler/msg_logout.go
- internal/handler/msg_saslcontinue.go
- internal/handler/msg_saslstart.go
- internal/handler/msg_saslstart_test.go
> Return `connectionStatus` command `db` field

- .golangci.yml
- internal/handler/msg_getlog.go
- internal/util/logging/buffer.go
- internal/util/logging/buffer_test.go
- internal/util/logging/handler_test.go
- internal/util/logging/logging.go
> Add stub for named `slog` logger helper

- .golangci-new.yml
- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/.golangci-new.yml
- integration/setup/startup.go
- internal/bson/types.go
- internal/handler/sjson/sjson.go
- internal/types/types.go
- internal/util/ctxutil/ctxutil.go
- internal/util/logging/logging.go
- internal/util/testutil/testtb/tb.go
Disable new linters that were not configured.
> Update linters configuration

- integration/setup/listener.go
- internal/handler/handler.go
- internal/handler/registry/hana.go
- internal/handler/registry/mysql.go
- internal/handler/registry/postgresql.go
- internal/handler/registry/sqlite.go
- website/docs/quickstart-guide/docker.md
Mainly for CI.
Also, add missing lazyerror chain elements.
> Increase setup timeout in tests

- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/listener.go
- internal/clientconn/conn.go
- internal/clientconn/listener.go
> Use `slog` in `clientconn` package

- cmd/envtool/envtool.go
- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/listener.go
- internal/backends/helpers_test.go
- internal/backends/postgresql/backend.go
- internal/backends/postgresql/database_test.go
- internal/backends/postgresql/metadata/pool/opendb.go
- internal/backends/postgresql/metadata/pool/pool.go
- internal/backends/postgresql/metadata/registry.go
- internal/backends/postgresql/metadata/registry_test.go
- internal/handler/registry/postgresql.go
- internal/handler/registry/registry.go
> Use `slog` in `postgresql` backend

- cmd/envtool/tests.go
- integration/setup/listener.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- internal/backends/backend.go
- internal/backends/collection.go
- internal/backends/database.go
- internal/clientconn/conn.go
- internal/handler/handler.go
> Add OTel spans

- integration/setup/listener.go
- integration/setup/setup.go
- integration/setup/setup_compat.go
- integration/setup/startup.go
- internal/util/logging/logging.go
- internal/util/logging/zap.go
- internal/util/testutil/logging.go
> Use `slog` in integration tests

- Taskfile.yml
- cmd/envtool/tests.go
- cmd/ferretdb/main.go
- integration/setup/startup.go
- internal/util/observability/observability.go
- website/docs/configuration/flags.md
- website/docs/configuration/observability.md
> Enable and document OTLP configuration

- go.mod
- go.sum
- integration/go.mod
- integration/go.sum
- internal/util/testutil/logging.go
We almost did it in #4481, but not quite.
> Drop old dependency

- internal/util/debug/debug.go
- internal/util/debug/debug_test.go
- website/docs/configuration/observability.md
DRY code, improve test.
Closes #3584.
> Refactor and document `/debug/archive` handler

- .github/workflows/docs.yml
- Taskfile.yml
> Fix `checkdocs` Github cache on CI

- website/blog/2024-08-07-build-restful-api-deno-oak-ferretdb.md
- website/static/img/blog/ferretdb-deno.jpg
- website/static/img/blog/ferretdb-deno/delete-record.png
- website/static/img/blog/ferretdb-deno/deno-connection.png
- website/static/img/blog/ferretdb-deno/get-records.png
- website/static/img/blog/ferretdb-deno/insert-record.png
- website/static/img/blog/ferretdb-deno/update-record.png
Closes FerretDB/engineering#184.
> Add blog post on building a RESTful API with Deno

- website/blog/2024-07-26-ferretdb-releases-v123-improved-observability.md
> Update missing image

- website/docs/quickstart-guide/deb.md
- website/docs/quickstart-guide/rpm.md
- website/docusaurus.config-blog.js
- website/docusaurus.config.js
- website/versioned_docs/version-v1.23/quickstart-guide/deb.md
- website/versioned_docs/version-v1.23/quickstart-guide/rpm.md
> Fix broken links

- build/deps/docusaurus-docs.Dockerfile
> Bump Docusaurus

- README.md
This PR introduces new one-click deployment option Elestio
Closes #4545
> Added Elestio as one-click deploy option

- internal/handler/cmd_query.go
- internal/handler/handlererrors/error.go
- internal/handler/handlererrors/errorcode_string.go
- internal/handler/msg_saslcontinue.go
> Support `saslStart` and `saslContinue` OpQuery

- website/blog/2024-08-28-ferretdb-releases-v124-sqlite-authentication-support.md
- website/static/img/blog/ferretdb-v1.24.0.jpg
> Add blog post for v1.24

- README.md
> Add Cozystack to README

- .github/workflows/packages.yml
- build/ferretdb/all-in-one.Dockerfile
- build/ferretdb/development.Dockerfile
- build/ferretdb/production.Dockerfile
- go.mod
- integration/go.mod
- tools/definedockertag/main.go
- tools/definedockertag/main_test.go
- tools/go.mod
- tools/go.sum
- tools/golangci/go.mod
- tools/tools.go
- website/go.mod
> Bump Go version

- internal/backends/mysql/mysql.go
The intention here should be to initialize a slice with a capacity of len(list) rather than initializing the length of this slice.
Closes #<issue_number>.
> Fix stats for MySQL backend

- .github/workflows/cleanup.yml
- .github/workflows/packages.yml
> Add separate CI job for defining Docker tags

- tools/definedockertag/main.go
- tools/definedockertag/main_test.go
> Update handling of all-in-one Docker images

- .github/workflows/conform-pr.yml
- .github/workflows/debug.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/go.yml
- .github/workflows/security.yml
- .github/workflows/testscripts.yml
- .github/workflows/website-preview.yml
- build/version/version.go
- tools/definedockertag/main.go
- tools/definedockertag/main_test.go
- website/docs/installation/ferretdb/docker.md
> Disable xfail CI configuration for now

- integration/shareddata/faker.go
- internal/mongoerrors/mongoerrors.go
- tools/checkcomments/checkcomments.go
- tools/checkcomments/testdata/testdata.go
- tools/definedockertag/main_test.go
Also added todos and made simple fixes to make CI pass.
Closes #4693.
> Skip private issue links in `checkcomments` by a flag

- .github/dependabot.yml
- .gitmodules
Those repositories are public now; no need to use secrets.
Closes #4694.
> Fix Dependabot config

- internal/mongoerrors/codes.go
- internal/mongoerrors/generate.go
- internal/mongoerrors/mongoerrors.go
> Fix error mapping generation

- .github/workflows/docs.yml
> Do not use Git LFS for Go files

- internal/documentdb/documentdb_api/documentdb_api.go
- internal/documentdb/genwrap/convert.go
- internal/documentdb/genwrap/convert_test.go
- internal/documentdb/genwrap/extract.go
- internal/documentdb/genwrap/extract_test.go
- internal/documentdb/genwrap/generate.go
- internal/documentdb/genwrap/generate_test.go
- internal/documentdb/genwrap/genwrap.go
Failing linter would be solved by #4695.
Closes #4700.
> Refactor extract and convert in `genwrap` tool

- internal/handler/handler.go
- internal/handler/msg_getlog.go
- internal/util/logging/buffer.go
- internal/util/logging/buffer_test.go
- internal/util/logging/handler.go
> Do not use a global variable for logging

- .github/ISSUE_TEMPLATE/chore.yml
> Remove "all backends" from the issue template

- website/docs/migration/migrating-from-mongodb.md
> Add missing space in command

- website/versioned_docs/version-v1.24/quickstart-guide/docker.md
- website/versioned_docs/version-v1.24/security/authentication.md
- website/versioned_docs/version-v1.24/security/tls-connections.md
To avoid breakage when v2 is tagged as `latest`.
> Update Docker image tag in v1 docs

- .github/workflows/docs.yml
- .github/workflows/website-preview.yml
- Taskfile.yml
- cmd/ferretdb/main.go
- integration/setup/listener.go
- internal/clientconn/listener.go
- internal/documentdb/pool_new.go
- internal/handler/handler.go
- tools/checkdocs/checkdocs.go
Just a small refactoring extracted from another issue.
> Make handler take over the pool

- .github/workflows/_integration.yml
- internal/dataapi/listener_test.go
- internal/documentdb/documentdb_test.go
- internal/documentdb/genwrap/extract_test.go
- internal/util/testutil/db.go
- internal/util/testutil/postgresql.go
Backport it from v1 as it becomes useful.
> Add test helper

- integration/findandmodify_compat_test.go
- website/docusaurus.config-blog.js
- website/docusaurus.config.js
> Tweak Docusaurus configuration

- .github/workflows/packages.yml
- CHANGELOG.md
- tools/definedockertag/main.go
- tools/definedockertag/main_test.go
> Update Docker tags

- Taskfile.yml
- internal/dataapi/listener.go
- internal/dataapi/listener_test.go
- internal/dataapi/server/server.go
- internal/util/debug/debug.go
> Make Data API without authentication if requested

- build/deps/postgres-documentdb.Dockerfile
- build/ferretdb-bw/Dockerfile
- build/ferretdb/evaluation.Dockerfile
- build/version/documentdb.go
- website/docs/guides/replication.md
- website/docs/security/authentication.md
- website/docs/security/tls-connections.md
> Update DocumentDB Docker image

- integration/update_field_compat_test.go
> Unskip tests that refer to closed issue

- integration/currentop_test.go
Closes #4871.
Please reopen the issue.
> Skip flaky `currentOp` test and add TODO

- website/blog/2025-03-05-ferretdb-v2-ga-open-source-mongodb-alternative-ready-for-production.md
- website/static/img/blog/ferretdb-v2-ga.png
> Add FerretDB v2 GA blog post

- internal/documentdb/pool_new.go
> Adjust pool connection timeout

- CHANGELOG.md
- Taskfile.yml
- build/deps/postgres-documentdb.Dockerfile
- build/ferretdb/evaluation.Dockerfile
- build/version/documentdb.go
- website/docs/installation/documentdb/docker.md
- website/docs/installation/ferretdb/docker.md
Per our new release checklist: https://github.com/FerretDB/FerretDB/blob/fb4d59f6a94909410d68388d9f53c0ea01b75b52/.github/RELEASE_CHECKLIST.md?plain=1#L58-L65
> Start working on a new release

- tools/checkdocs/checkdocs.go
- tools/checkdocs/checkdocs_test.go
> Check issue URLs in documentation

- .github/workflows/testscripts.yml
- integration/commands_diagnostic_test.go
- integration/cursor/batch_test.go
- integration/cursor/getmore_test.go
- integration/setup/setup.go
- internal/handler/handler.go
Just a small refactoring for the next PR.
> Configure connection pool size in tests

- .github/PROCESS.md
Expand process documentation a bit.
> Add a note to documentation about PR titles

- integration/Taskfile.yml
- integration/setup/setup.go
- integration/setup/startup.go
> Disable tracing in benchmarks for now

- website/blog/2025-03-27-20-must-try-mongodb-queries-operations-ferretdb.md
Closes FerretDB/engineering#235.
> Update feature blog post

- integration/basic_test.go
- integration/setup/setup.go
- internal/handler/msg_ferretdebugerror.go
> Add more tests for error handling

- .github/RELEASE_CHECKLIST.md
- website/docusaurus.config.js
> Create redirects for `/v2.0/` documentation URLs

- CHANGELOG.md
- README.md
- build/deps/postgres-documentdb.Dockerfile
- build/ferretdb/evaluation.Dockerfile
- build/version/documentdb.go
- internal/documentdb/pool_new.go
- website/docs/installation/documentdb/docker.md
- website/docs/installation/ferretdb/docker.md
> Update Docker images

- integration/auth_test.go
- integration/currentop_test.go
- integration/indexes_command_test.go
- integration/integration.go
- integration/op_query_test.go
- integration/session/endsessions_test.go
- integration/session/killallsessions_test.go
- integration/session/killallsessionsbypattern_test.go
- integration/session/killsessions_test.go
- integration/session/refreshsessions_test.go
- integration/session/startsession_test.go
> Move tests for sessions

- internal/clientconn/conn.go
- internal/handler/proxy/proxy.go
> Minor tweaks for proxy code

- README.md
- website/docs/troubleshooting/overview.md
- website/versioned_docs/version-v2.0/troubleshooting/overview.md
- website/versioned_docs/version-v2.1/troubleshooting/overview.md
> Use "PostgreSQL with DocumentDB extension" phrase

- website/versioned_docs/version-v2.1/installation/documentdb/deb.md
- website/versioned_docs/version-v2.1/installation/documentdb/kubernetes.md
- website/versioned_docs/version-v2.1/installation/ferretdb/deb.md
- website/versioned_docs/version-v2.1/installation/ferretdb/kubernetes.md
- website/versioned_docs/version-v2.1/installation/ferretdb/macos.md
- website/versioned_docs/version-v2.1/installation/ferretdb/rpm.md
- website/versioned_docs/version-v2.1/installation/ferretdb/systemd.md
- website/versioned_docs/version-v2.1/installation/ferretdb/windows.md
> Backport Kubernetes docs to 2.1

- website/versioned_docs/version-v2.1/installation/documentdb/deb.md
> Backport `.deb` installation guide

- website/docs/guides/vector-search.mdx
> Unconvert syntax examples in documentation

- integration/indexes_command_compat_test.go
- integration/indexes_compat_test.go
- internal/documentdb/bsonhex/decoder.go
- internal/documentdb/documentdb_api/documentdb_api.go
- internal/documentdb/documentdb_api/procedure.go
- internal/documentdb/documentdb_api_internal/documentdb_api_internal.go
- internal/documentdb/documentdb_api_procedure/procedure.go
- internal/documentdb/genwrap/convert.go
- internal/documentdb/genwrap/convert_test.go
- internal/documentdb/genwrap/generate.go
- internal/handler/msg_dropindexes.go
- internal/handler/msg_reindex.go
> Decode `dropIndexes` response

- Taskfile.yml
- tools/go.mod
- tools/go.sum
- website/docs/guides/ttl-indexes.json
- website/docs/guides/ttl-indexes/1-create-ttl-index.request.js
- website/docs/guides/ttl-indexes/1-create-ttl-index.response.js
- website/docs/guides/ttl-indexes/2-insert-ttl-data.request.js
> Run CTS tests against TTL Indexes guide examples

- website/docs/guides/replication.md
- website/docs/installation/ferretdb/docker.md
- website/docs/security/authentication.md
- website/docs/security/tls-connections.md
- website/versioned_docs/version-v2.0/guides/replication.md
- website/versioned_docs/version-v2.0/installation/ferretdb/docker.md
- website/versioned_docs/version-v2.0/security/authentication.md
- website/versioned_docs/version-v2.0/security/tls-connections.md
- website/versioned_docs/version-v2.1/guides/replication.md
- website/versioned_docs/version-v2.1/installation/ferretdb/docker.md
- website/versioned_docs/version-v2.1/security/authentication.md
- website/versioned_docs/version-v2.1/security/tls-connections.md
> Remove old TODOs

- website/docs/configuration/observability.md
- website/docs/installation/documentdb/deb.md
- website/docs/installation/documentdb/docker.md
- website/docs/installation/ferretdb/deb.md
- website/docs/installation/ferretdb/docker.md
> Document update process for new releases

- build/deps/postgres-documentdb.Dockerfile
- build/ferretdb/eval-dev.Dockerfile
- build/ferretdb/eval.Dockerfile
- build/version/documentdb.go
- integration/commands_administration_test.go
- internal/documentdb/documentdb_api_internal/documentdb_api_internal.go
- internal/documentdb/documentdb_test.go
- website/docs/contributing/writing-guide.md
- website/docs/installation/documentdb/docker.md
- website/docs/installation/documentdb/kubernetes.md
- website/docs/installation/ferretdb/docker.md
- website/docs/installation/ferretdb/kubernetes.md
- website/docs/usage/data-api.md
And update tests to work on arm64.
> Update versions to point to the next release

- website/versioned_docs/version-v2.2/installation/ferretdb/docker.md
> Update docker tags in docs

- website/docs/installation/ferretdb/docker.md
> Update tags for next release

- .github/workflows/cleanup.yml
- .github/workflows/cts.yml
- .github/workflows/debug.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/go.yml
- .github/workflows/security.yml
- .github/workflows/testscripts.yml
- .github/workflows/website-preview.yml
> Add `permissions` to GitHub Actions workflows

- integration/delete_test.go
> Unskip test

- .gitignore
- Taskfile.yml
- docker-compose.override.yml.example
> Use Ollama in local setup

- website/docs/compatible-applications/applications.js
- website/versioned_docs/version-v2.3/compatible-applications/applications.js
> Add Compass to compatible apps

- website/blog/2025-06-25-building-scalable-community-forums-nodebb-and-ferretdb.md
- website/static/img/blog/ferretdb-nodebb.jpg
- website/static/img/blog/nodebb-admin-dashboard.png
- website/static/img/blog/nodebb-compass.png
- website/static/img/blog/nodebb-topic.png
> Add NodeBB compatibility blog post

- .github/dependabot.yml
> Add Dependabot configuration for mcphost

- cmd/ferretdb/main_test.go
- integration/indexes_compat_test.go
- integration/setup/helpers.go
- integration/setup/listener.go
- internal/documentdb/genwrap/generate_test.go
- internal/handler/cmd_query.go
- internal/handler/middleware/request.go
- internal/handler/middleware/response.go
- internal/handler/proxy/proxy.go
- internal/util/debug/archive.go
- internal/util/debug/debug.go
- internal/util/telemetry/reporter.go
- internal/util/telemetry/telemetry_test.go
> Extend middleware requests and responses

- cmd/ferretdb/main.go
- ferretdb/ferretdb.go
- integration/setup/listener.go
- internal/clientconn/conn.go
- internal/clientconn/listener.go
- internal/dataapi/listener_test.go
- internal/handler/commands.go
- internal/handler/handler.go
- internal/handler/middleware/middleware.go
- internal/handler/middleware/mode.go
- internal/handler/middleware/response.go
- internal/handler/proxy/proxy.go
> Split command handling and handlers

- .github/codecov.yml
> Add components in codecov

- website/blog/2025-07-23-dynamic-database-credentials-with-hashicorp-vault-and-ferretdb.md
- website/docs/compatible-applications/applications.js
- website/static/img/blog/ferretdb-vault.jpg
- website/static/img/compatible-applications/vault-logo.png
- website/versioned_docs/version-v2.4/compatible-applications/applications.js
> Add Vault blog post

- cmd/ferretdb/gomaxprocs.go
- cmd/ferretdb/main.go
- internal/dataapi/listener.go
- internal/util/setup/setup.go
> Small cleanup

- internal/documentdb/pool.go
- internal/handler/middleware/response.go
- internal/util/logging/buffer_test.go
- internal/util/logging/logging.go
- internal/util/observability/propagation.go
- internal/util/observability/propagation_test.go
- internal/util/telemetry/reporter_test.go
- internal/util/testutil/teststress/stress.go
- internal/util/testutil/testutil.go
- tools/github/github_test.go
Assorted fixed to make the other PR smaller.
Closes #4965.
> Small tweaks

- build/mongodb-secure.conf
- build/mongodb.conf
> Enable MongoDB test commands

- build/deps/yugabytedb.Dockerfile
Closes #5425.
https://docs.yugabyte.com/preview/releases/ybdb-releases/v2025.1/
> Bump YugabyteDB to stable version

- cmd/envtool/envtool.go
- cmd/envtool/setup.go
- docker-compose.yml
> Use QEMU on arm64 for Yugabyte for now

- website/blog/_guide/content-process.md
> Update content guide

- website/docs/compatible-applications/applications.js
- website/static/img/compatible-applications/formio-logo.jpeg
- website/versioned_docs/version-v2.5/compatible-applications/applications.js
> Update compatible apps

- build/ferretdb/development.Dockerfile
- build/ferretdb/eval-dev.Dockerfile
- build/ferretdb/eval.Dockerfile
- build/ferretdb/production.Dockerfile
- build/version/documentdb.go
> Add TODO comment about Debian 13 Trixie

- README.md
- integration/indexes_compat_test.go
- internal/documentdb/documentdb.go
- internal/documentdb/documentdb_api/procedure.go
- internal/documentdb/genwrap/convert.go
- internal/handler/commands.go
- internal/handler/handler.go
- internal/handler/middleware/response.go
- internal/handler/msg_createindexes.go
- internal/handler/msg_listdatabases.go
- internal/mongoerrors/mongoerrors.go
- tools/checkcomments/checkcomments.go
- tools/checkcomments/testdata/testdata.go
- tools/checkdocs/checkdocs.go
- tools/checkdocs/checkdocs_test.go
- tools/github/github_test.go
- website/docs/installation/documentdb/deb.md
- website/docs/installation/documentdb/docker.md
- website/docs/installation/documentdb/kubernetes.md
- website/docs/introduction.md
> Move to `documentdb/documentdb`
