CONTRIBUTING.md
I got stuck on checking `go version` after installing` gotip`, it didn't show `1.18`. After googling, I figured out that `gotip version` is the command that I need to run.
=> Update `contributing` document.

internal/pg/pool.go, internal/pg/pool_test.go
=> Make `checkConnection` less strict for common UTF8 localizations.

internal/handlers/handler.go, internal/handlers/handler_test.go, internal/handlers/shared/msg_create.go
=> Implement basic `create` command.

internal/util/version/version.go
It was changed at
https://github.com/golang/go/commit/931d80ec17374e52dbc5f9f63120f8deb80b355d
=> Fix build info parsing.

internal/handlers/handler_test.go, internal/handlers/shared/msg_buildinfo.go, internal/util/version/version.go
PR for #197 and #198.
Although I'm not completely sure about obtaining the value of architecture bits, but adding another flag to `buildInfo.Settings` seems a bit cleaner than parsing `GOARCH` (especially if you consider that, for example, `amd64p32` is a valid 32-bit compilation target).
=> Improve output of buildInfo command

.github/workflows/containers.yml
Build containers for branches as well.
=> Build containers for branches as well.

internal/bson/bson_test.go, internal/types/document.go, internal/types/document_test.go, internal/wire/op_msg_test.go, internal/wire/wire_test.go
=> Forbid short document keys like `$k`

.golangci.yml, CONTRIBUTING.md, internal/bson/bson.go, internal/bson/document.go, internal/clientconn/conn.go, internal/fjson/fjson.go, internal/handlers/handler_test.go, internal/handlers/msg_buildinfo.go, internal/handlers/msg_getcmdlineopts.go, internal/handlers/msg_hello.go, internal/handlers/query_cmd.go, internal/types/array.go, internal/types/binary.go, internal/types/types.go, internal/wire/op_msg.go, internal/wire/op_query.go, internal/wire/op_reply.go, internal/wire/wire.go
=> Update documentation about `fjson` package

internal/bson/array.go, internal/bson/array_test.go, internal/bson/binary.go, internal/bson/binary_test.go, internal/bson/bool.go, internal/bson/bool_test.go, internal/bson/bson.go, internal/bson/bson_test.go, internal/bson/datetime.go, internal/bson/datetime_test.go, internal/bson/document.go, internal/bson/double.go, internal/bson/double_test.go, internal/bson/int32.go, internal/bson/int32_test.go, internal/bson/int64.go, internal/bson/int64_test.go, internal/bson/objectid.go, internal/bson/objectid_test.go, internal/bson/regex.go, internal/bson/regex_test.go, internal/bson/string.go, internal/bson/string_test.go, internal/bson/timestamp.go, internal/bson/timestamp_test.go, internal/types/types.go
=> Unexport some `bson` types

internal/handlers/handler.go, internal/handlers/handler_test.go, internal/handlers/msg_dbstats.go, internal/handlers/msg_listcollections.go, internal/handlers/msg_listdatabases.go, internal/pg/pool.go, internal/pg/pool_test.go, internal/util/testutil/testutil.go
=> Catch concurrent schema/table creation

README.md
fix 2 issues:
1. when create `docker-copose.yml` in `test` folder ,`docker-compose up` will  create a network `test_default` but not `ferretdb_default` . it will make the command 
`docker run --rm -it --network=ferretdb_default --entrypoint=mongosh mongo:5 mongodb://ferretdb/` not work.
2. docker compose not start in correct order ,add depends_on to make sure everything run in order.
error log I met when not add depends_on:
```
(virtualenv) [centos@localhost ~]$ sudo docker-compose up
Starting postgres ...
Recreating ferretdb ...
Recreating ferretdb ... done
Attaching to postgres, postgres_setup, ferretdb
postgres          |
postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres          |
postgres          | 2022-01-19 …
```
=> Update tutorial ,add depends_on in docker-compose

cmd/ferretdb/main.go, internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/handler.go, internal/handlers/handler_test.go, internal/handlers/msg_serverstatus.go
Closes #156 
Output example:
```sh
test> db.serverStatus()
{
host: 'demo-ubuntu',
version: '5.0.42',
process: 'ferretdb-testcover',
pid: Long("1900"),
uptime: Long("2"),
uptimeMillis: Long("2426"),
uptimeEstimate: Long("2"),
localTime: ISODate("2022-01-26T19:24:32.956Z"),
catalogStats: {
collections: 0,
capped: 0,
timeseries: 0,
views: 0,
internalCollections: 0,
internalViews: 0
},
freeMonitoring: { state: 'disabled' },
ok: 1
}
````
=> Support `serverStatus`.

internal/handlers/msg_listcollections.go, internal/handlers/msg_listdatabases.go
=> Ignore some parameters

internal/handlers/command.go
There is a dangling white space in the "insert" command's help string. This PR fixes it ;)
=> Update `insert` command's help

internal/handlers/common/required.go, internal/handlers/handler.go, internal/handlers/jsonb1/msg_delete.go, internal/handlers/jsonb1/msg_find_or_count.go, internal/handlers/jsonb1/msg_insert.go, internal/handlers/jsonb1/msg_update.go, internal/handlers/msg_collstats.go, internal/handlers/msg_create.go, internal/handlers/msg_dbstats.go, internal/handlers/msg_drop.go, internal/handlers/msg_dropdatabase.go, internal/handlers/msg_listcollections.go, internal/handlers/msg_serverstatus.go, internal/handlers/sql/msg_delete.go, internal/handlers/sql/msg_find_or_count.go, internal/handlers/sql/msg_insert.go
=> Add helper for getting required parameters

integration/commands_replication_test.go, internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/handler_test.go
Propagate test-scoped logger everywhere.
Refs #411.
=> Improve logging in integration tests

integration/basic_test.go, integration/commands_administration_test.go, integration/query_array_test.go, integration/query_bitwise_test.go, internal/handlers/handler_test.go, internal/handlers/pg/msg_getparameter.go
=> Move `getParameter` tests

integration/helpers.go, integration/query_comparision_test.go, integration/shareddata/scalars.go, internal/handlers/common/compare.go, internal/handlers/common/filter.go, internal/handlers/handler_test.go
This PR rearranges our integration tests, adds more test cases, and fixes small bugs in regex handling.
(do not miss the large diff of integration/query_comparision_test.go that is not rendered by default)
=> Rearrange tests

internal/util/testutil/equal.go
=> Make test helpers harder to misuse

integration/query_test.go, internal/handlers/common/error.go, internal/handlers/common/errorcode_string.go, internal/handlers/common/filter.go, internal/handlers/common/typecode.go, internal/handlers/common/typecode_test.go, internal/handlers/pg/msg_find.go
=> Add tests for `sort` and `find` parameters type

integration/query_projection_test.go, integration/query_test.go, integration/shareddata/bignumbers.go, integration/shareddata/composites.go, internal/handlers/common/match.go, internal/types/compare.go, internal/util/testutil/equal.go, internal/util/testutil/equal_test.go
=> Add documentation for values comparision

CONTRIBUTING.md
The original purpose of this change was to correct a typo.
Though, after re-reading the text, I believe it's better to call `cmd` _directory_, not _package_. All the packages inside `cmd` are called `main` ;)
It could be a bit opinionated, so feel free to reject if you disagree.
=> Update CONTRIBUTING.md with typo fix and a tiny correction

integration/basic_test.go, internal/handlers/common/msg_listcommands.go
The former is sent by the old `mongo` shell.
=> Handle both `buildinfo` and `buildInfo` commands

internal/types/array.go, internal/types/array_test.go
Closes #637.
This implementation covers all scalar types. To cover composite, first need to implement `comparison order` of composite data types #457.
=> Add `Min` and `Max` methods to `types.Array`

integration/query_array_test.go, integration/query_comparison_test.go, integration/query_element_test.go, integration/query_logical_test.go, integration/query_test.go, integration/shareddata/composites.go
This PR provides additional examples for tests' shared data composites. 
These examples will help to cover more test cases. 
For example, they are helpful for #724.
Also, `array-empty-nested` reveals a bug described in #732.
- Take a look at the changes in `integration/shareddata/composites.go`.
- Take a look at the rest of the files. Various tests were rewritten to support new composites.
=> Add arrays with `NaN`, `double` and nested empty array to tests' shared data

integration/commands_administration_test.go
We run a lot of tests in parallel, so the number of collections is in the range between 1 (this test) and many, where "many" is 100 for now.
Uptime can also be as small as 0 seconds on a fast machine but can also be large if the environment wasn't restarted for a long time.
=> Fix fluky test

integration/commands_freemonitoring_test.go, internal/handlers/common/error.go, internal/handlers/common/errorcode_string.go, internal/handlers/common/msg_listcommands.go, internal/handlers/common/msg_setfreemonitoring.go, internal/handlers/dummy/msg_setfreemonitoring.go, internal/handlers/handlers.go, internal/handlers/pg/msg_setfreemonitoring.go, internal/handlers/tigris/msg_setfreemonitoring.go
=> Implement `setFreeMonitoring` stub

Taskfile.yml, cmd/envtool/main.go, docker-compose.yml, integration/commands_administration_test.go, internal/handlers/pg/pgdb/pool_test.go
We are not using it much now, but it makes `task env-up` much slower.
=> Drop `test_db`

CHANGELOG.md, tools/go.mod, tools/go.sum, tools/tools.go
=> Add `godoc` to tools

.github/workflows/docker.yml, .github/workflows/go.yml, .github/workflows/integration.yml
Sync FerretDB's and dance's build times, so dance tests run after the new Docker image is built.
See FerretDB/dance#146.
=> Tweak schedule of daily builds

Taskfile.yml
After the switch from `image` to `build` in `docker-compose.yml`,
the previous command did nothing useful.
=> Fix `task env-pull` target

.github/workflows/conform-pr.yml, .github/workflows/docker.yml, .github/workflows/go.yml, .github/workflows/integration.yml
This makes it easier to solve problems like this one:
To trigger rebuild, re-enable auto-merge.
=> Make it easier to trigger rebuilds

integration/basic_test.go, integration/commands_administration_test.go, integration/commands_diagnostic_test.go, integration/commands_freemonitoring_test.go, integration/commands_replication_test.go, integration/delete_test.go, integration/findandmodify_test.go, integration/query_array_test.go, integration/query_bitwise_test.go, integration/query_comparison_test.go, integration/query_element_test.go, integration/query_evaluation_test.go, integration/query_logical_test.go, integration/query_projection_test.go, integration/query_test.go, integration/setup.go, integration/shareddata_test.go, integration/update_field_test.go, integration/update_test.go
They are needed for Tigris integration.
=> Export integration tests helpers

cmd/envtool/main.go
=> Create Tigris databases

cmd/envtool/main.go
That should solve `task env-up` problems.
=> Wait for Tigris to be fully up

README.md
=> Document that NUL (`\0`) strings is not supported

Dockerfile, Taskfile.yml, cmd/ferretdb/main_test.go, cmd/ferretdb/main_tigris.go, internal/handlers/registry/tigris.go, internal/util/version/version.go
=> Add `ferretdb_` prefix to our custom build tags

integration/commands_administration_test.go, integration/setup.go, internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/pg/msg_drop.go, internal/handlers/pg/msg_listcollections.go, internal/handlers/tigris/msg_insert.go
Errors are different when dropping non-existing collections in existing vs non-existing databases, etc.
=> Fix edge cases in `drop` and `dropDatabase` handlers

Taskfile.yml, cmd/envtool/main.go
* adds wait for Tigris backend in envtool.
* adds `docker buildx prune` in `init-clean`
* adds `docker system prune` including volume in `init-clean`
It might seem too much for one.
If you don't want to prune all docker volumes, feel free to say `No` to that when it asks. 
Task continues to run without pruning docker volumes.
=> Wait for `Tigris` backend to be ready

internal/handlers/pg/pgdb/collections.go
This PR is created to fix failing tests on `main`, e.g. [here](https://github.com/FerretDB/FerretDB/runs/7356655044?check_suite_focus=true).
=> Handle `42P07` PostgreSQL error to fix the tests

internal/handlers/pg/msg_count.go, internal/handlers/pg/msg_dbstats.go, internal/handlers/pg/msg_delete.go, internal/handlers/pg/msg_find.go, internal/handlers/pg/msg_findandmodify.go, internal/handlers/pg/msg_insert.go, internal/handlers/pg/msg_update.go, internal/handlers/pg/pg.go, internal/handlers/pg/pgdb/query_documents.go, internal/handlers/pg/pgdb/query_documents_test.go
This PR is a part of #167.
Explain command will add yet another parameter to the `QueryDocuments`, so this PR gathers `QueryDocuments` parameters at one variable.
=> Extract parameter list into one variable in `QueryDocuments`

integration/findandmodify_test.go, integration/query_array_test.go, integration/query_bitwise_test.go, integration/query_comparison_test.go, integration/query_element_test.go, integration/query_evaluation_test.go, integration/query_logical_compat_test.go, integration/query_logical_test.go, integration/query_projection_test.go, integration/query_test.go, integration/shareddata/shareddata.go, integration/update_field_compat_test.go, integration/update_field_test.go, internal/handlers/common/update.go
`value` is a reserved field name in Tigris.
Refs #786.
=> Use `v` instead of `value` in tests

.codecov.yml, .github/workflows/go.yml, .github/workflows/integration.yml, Taskfile.yml
Prevents bogus "FerretDB Check codecov/project failed for branch: main" messages in Slack.
=> Tweak codecov settings

cmd/envtool/main.go, internal/handlers/pg/msg_drop.go, internal/handlers/pg/msg_listcollections.go, internal/handlers/pg/msg_listdatabases.go, internal/handlers/pg/pgdb/pool.go, internal/handlers/pg/pgdb/pool_test.go
Remove deprecated `Schema` and use `Databases` instead (in transaction).
=> Remove deprecated functions from `pgdb.Pool`

integration/setup.go
This PR comments `url.Values` in the `setupClient` function to prevent timeout errors in tests. Further investigation will be required.
=> comment `url.Values` to prevent test failing

README.md, integration/basic_test.go
This PR closes #807.
- fix typo in documentation
- add test border case 63 and 64 letters in a database name.
=> Add test for a database name border case

integration/setup/setup.go
Added comment to the setup function:
> Add comment to the setup function about database and collection creation when provider list is empty.
=> Add a comment to the setup function about database and collection creation when provider list is empty

internal/types/path_test.go
=> Add Path tests

integration/update_field_test.go, internal/handlers/common/update.go
=> Fix `nModified` count for `update`'s `$set` operator with the same value

integration/basic_test.go, integration/commands_administration_test.go, internal/handlers/pg/msg_listdatabases.go, internal/util/testutil/db.go
Closes #952.
Relevant PostgreSQL docs from https://www.postgresql.org/docs/current/sql-syntax-lexical.html
> Key words and unquoted identifiers are case insensitive.
> ...
> Quoting an identifier also makes it case-sensitive
=> Fix some collection names breaking `listDatabases`

integration/query_compat_test.go, integration/query_logical_compat_test.go
=> Add compatibility tests for `$and`

internal/tjson/binary_test.go, internal/tjson/bool_test.go, internal/tjson/double_test.go, internal/tjson/int32_test.go, internal/tjson/int64_test.go, internal/tjson/string_test.go, internal/tjson/tjson_test.go
This PR is a part of #900. 
In the scope of the PR:
- port tests for `binary`
- simplify `fuzz` and `benchmark` signatures (they don't need types)
=> `tjson`: Check how we support `binary`

integration/findandmodify_test.go, integration/query_test.go, internal/handlers/tigris/msg_find.go
This PR adds a couple of missing things left after #608:
- the `findAndModify` part of the tests was moved to the correct file
- `maxTimeMS` was removed from unsupported fields for Tigris (as it was implemented in #608)
=> Add missing `MaxTimeMS` support for Tigris

build/deps/tigris.Dockerfile
Let's bump Tigris to 1.0.0-alpha.27 as it has some nice fixes about setting `null` when running update operations.
=> Bump Tigris version to 1.0.0-alpha.27

integration/delete_compat_test.go, integration/query_compat_test.go, integration/query_logical_compat_test.go, integration/update_compat_test.go
=> Add a few more tests for logical query operators

integration/commands_administration_test.go, internal/handlers/tigris/msg_dbstats.go
=> Implement `MsgDBStats` for Tigris

integration/update_compat_test.go, internal/handlers/common/update.go
This PR closes #1045.
Basically I'am removing all keys `(!= _id)` when receiving an empty update object.
=> Fix `ModifiedCount` for updates with an empty replacement document

integration/update_field_test.go
A part of parallel test cases was shared and modified by them.
Noticed at https://github.com/FerretDB/FerretDB/runs/7993947283?check_suite_focus=true.
=> Fix data race in test

.github/workflows/go.yml, .github/workflows/integration.yml
That should make codecov uploads more stable.
=> Use `CODECOV_TOKEN` if available

build/deps/markdownlint.Dockerfile, build/deps/tigris.Dockerfile, go.mod, go.sum, integration/go.mod, integration/go.sum
=> Bump dependencies

integration/findandmodify_test.go, integration/update_test.go, internal/handlers/pg/msg_findandmodify.go
=> Handle `findAndModify` and `update` correctly when collection doesn't exist

integration/delete_compat_test.go, integration/helpers.go, internal/handlers/common/error.go, internal/handlers/pg/msg_delete.go, internal/handlers/tigris/msg_create.go, internal/handlers/tigris/msg_delete.go
=> Simplify/sync `delete` a bit

.gitignore, Taskfile.yml
=> Use fixed `-test-record` directory in Task targets

README.md, website/docs/diff.md, website/docs/intro.md
=> DRY known differences documentation

integration/commands_administration_test.go
=> Fix fluky test, refactor it

cmd/envtool/main.go
=> Migrate envtool to Kong

go.mod, internal/handlers/pg/msg_listcollections.go, internal/handlers/pg/pgdb/collections.go, internal/handlers/pg/pgdb/pgdb_test.go, internal/handlers/pg/pgdb/query.go, internal/handlers/pg/pgdb/schemas.go, internal/handlers/pg/pgdb/settings.go, internal/handlers/pg/pgdb/tables.go
=> Replace `pgxtype.Querier` with `pgx.Tx`

integration/setup/setup.go, integration/setup/setup_compat.go, internal/handlers/pg/pgdb/settings.go
=> Cleanup `pgdb` SQL statements

ferretdb/ferretdb.go, ferretdb/ferretdb_test.go, integration/embedded_test.go
That also fixes ports conflicts when tests are run in parallel.
=> Make embedded FerretDB's address configurable

.github/workflows/go.yml, .github/workflows/integration.yml
Refs codecov/codecov-action#837.
=> Use codecov upload token

internal/handlers/pg/msg_findandmodify.go, internal/handlers/pg/msg_update.go
This PR refs #1203.
This PR didn't fix the tests, but I consider it an improvement, so please review.
Next step (after this PR is merged): the exact change for `h.insert`.
=> Use single transaction per `msg_update` request

internal/handlers/pg/msg_findandmodify.go, internal/handlers/pg/msg_insert.go, internal/handlers/pg/msg_update.go
This PR refs #1203.
This PR didn't fix the tests, but I consider it an improvement, so please review.
=> Use single transaction per `msg_insert` request

website/docs/contributing.md
=> Documentation for contributors

integration/create_test.go, integration/findandmodify_compat_test.go, integration/setup/common.go, integration/setup/setup.go, integration/setup/setup_compat.go, integration/shareddata_test.go, integration/update_field_compat_test.go, internal/util/testutil/db.go
=> Fix running `pg` and `tigris` tests in parallel

.gitignore, Taskfile.yml, cmd/envtool/main.go, cmd/ferretdb/main.go, cmd/ferretdb/main_test.go, cmd/ferretdb/main_tigris.go, cmd/fuzztool/fuzztool.go, ferretdb/ferretdb.go, go.mod, integration/setup/common.go, internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/pg/msg_getlog.go, internal/handlers/tigris/msg_getlog.go, internal/util/logging/buffer.go, internal/util/logging/buffer_test.go, internal/util/logging/logging.go, internal/util/state/state.go, internal/util/state/state_test.go, internal/util/version/generate.go
=> Add UUID to log messages

cmd/ferretdb/main.go, cmd/ferretdb/main_tigris.go, internal/handlers/pg/msg_explain.go
=> Fix CLI flags for Tigris

internal/handlers/pg/msg_collstats.go, internal/handlers/pg/msg_count.go, internal/handlers/pg/msg_create.go, internal/handlers/pg/msg_createindexes.go, internal/handlers/pg/msg_datasize.go, internal/handlers/pg/msg_dbstats.go, internal/handlers/pg/msg_delete.go, internal/handlers/pg/msg_drop.go, internal/handlers/pg/msg_dropdatabase.go, internal/handlers/pg/msg_explain.go, internal/handlers/pg/msg_find.go, internal/handlers/pg/msg_findandmodify.go, internal/handlers/pg/msg_getlog.go, internal/handlers/pg/msg_getparameter.go, internal/handlers/pg/msg_hello.go, internal/handlers/pg/msg_insert.go, internal/handlers/pg/msg_ismaster.go, internal/handlers/pg/msg_listcollections.go, internal/handlers/pg/msg_listdatabases.go, internal/handlers/pg/msg_ping.go, internal/handlers/pg/msg_serverstatus.go, internal/handlers/pg/msg_update.go, internal/handlers/pg/pg.go, internal/handlers/tigris/msg_count.go, internal/handlers/tigris/msg_create.go, internal/handlers/tigris/msg_delete.go, internal/handlers/tigris/msg_find.go, internal/handlers/tigris/msg_update.go
=> Minor handlers refactoring

internal/handlers/pg/pjson/pjson.go, internal/handlers/pg/pjson/pjson_test.go
=> Skip `pjson` fuzzing of invalid documents for now

cmd/ferretdb/main.go, cmd/ferretdb/main_unix.go, internal/handlers/pg/pgdb/query_test.go, internal/util/testutil/testutil.go, internal/util/testutil/testutil_unix.go, internal/util/testutil/testutil_windows.go
That should make tests more stable.
=> Improve tests cleanup

internal/types/types.go
I noticed this typo while reviewing https://github.com/FerretDB/FerretDB/pull/1291 (the typo is not relevant to the PRs, I was just checking the places where `tjson` is mentioned). As the main PR was already merged, this is a separate one to fix the typo.
=> Fix a typo in the `types` package docs

integration/setup/common_unix.go
=> Disable Unix sockets in tests for now

internal/handlers/tigris/tjson/schema.go, internal/handlers/tigris/tjson/schema_test.go, internal/handlers/tigris/tjson/tjson_test.go
=> Fix `tjson` schema unmarshalling

website/docs/diff.md
=> A minor clarification about diff tests

.markdownlint.yml, Taskfile.yml, website/docs/understanding_ferretdb.md
Those documents are not valid JSON.
=> Fix syntax highlighting

integration/insert_compat_test.go, integration/query_compat_test.go, integration/update_compat_test.go, internal/handlers/common/error.go, internal/types/document_validation.go
This PR tweak compatibility tests to make them look a bit closer to each other.
=> Cleanup compat tests

.textlintignore, Taskfile.yml
Even if `node_modules` directory is present on the host for any reason, it should be ignored by linters.
=> Fix ignore patterns for tools

Dockerfile, Taskfile.yml
=> Provide builds for `linux/arm/v7`

integration/commands_replication_test.go, internal/handlers/common/common.go, internal/handlers/pg/cmd_query.go, internal/handlers/pg/msg_hello.go, internal/handlers/pg/msg_ismaster.go, internal/handlers/tigris/cmd_query.go, internal/handlers/tigris/msg_hello.go, internal/handlers/tigris/msg_ismaster.go
We don't actively test with 5.1, but that allows us to support some software that wasn't updated for 6.0 yet.
=> Tweak supported wire protocol versions

.github/workflows/conform-pr.yml
That should make restarts easier.
=> Do not cancel in-progress CI runs

.github/workflows/conform-pr.yml, integration/.golangci-new.yml, integration/commands_administration_test.go, integration/create_test.go, integration/helpers.go, internal/handlers/pg/msg_listdatabases.go, internal/handlers/pg/pgdb/collections.go, internal/handlers/pg/pgdb/settings.go, internal/handlers/tigris/msg_create.go, internal/handlers/tigris/tigrisdb/errors.go
Closes #1206.
Note: I didn't refactor how the settings table is used (as it's not in the scope of the task), I only fixed the exact problem with missing locks.
=> Add missing locks when update settings table

internal/handlers/common/serverstatus.go, internal/handlers/pg/msg_getlog.go, internal/handlers/tigris/msg_getlog.go, internal/util/state/metrics.go, internal/util/telemetry/reporter.go, internal/util/telemetry/reporter_test.go, internal/util/telemetry/telemetry.go, internal/util/telemetry/telemetry_test.go
=> Minor telemetry cleanup

website/docs/reference/supported_commands.md
=> Fix information about `delete`'s `comment` argument inside "supported commands" reference

website/docs/reference/supported_commands.md
=> Add query plan cache commands to the docs

.github/workflows/integration.yml
As we don't have plans to support CockroachDB soon, let's disable it running on CI.
I also created a ticket to add basic support #1523.
=> Disable CockroachDB on GitHub Actions

.gitignore, Taskfile.yml, docker-compose.yml
Testing scripts could be put into `build/mongosh/test.js` to be executed by `task mongosh`.
=> Add placeholder for testing scripts

.github/workflows/integration.yml, integration/basic_test.go, integration/query_array_compat_test.go, integration/query_array_test.go, integration/query_compat_test.go, integration/query_test.go
Closes #1450.
This is one of many PR to move query integration tests to compat tests. This PR moves array query tests to compat test.
The tests that were not moved were
* Requires additional test Bson in shareddata, and currently adding that is too painful because too many tests are failing. This will be done once more tests were moved to compat, that will make it easier.
* Nan and Negative Zero because they will be removed by https://github.com/FerretDB/FerretDB/pull/1401
* Others that were not moved have TODO with issue link attached.
=> Move array query tests to compat tests

integration/commands_replication_test.go, internal/handlers/common/common.go
=> Downgrade min wire protocol version to 13 / 5.0

cmd/ferretdb/main.go
Before:
```
--telemetry=                                                      Enable or disable basic telemetry. See https://beacon.ferretdb.io ($FERRETDB_TELEMETRY).
```
After:
```
--telemetry=undecided                                             Enable or disable basic telemetry. See https://beacon.ferretdb.io ($FERRETDB_TELEMETRY).
```
=> Make default telemetry state a bit more clear

internal/clientconn/conn.go, internal/clientconn/listener.go, internal/wire/msg_body.go, internal/wire/msg_header.go, internal/wire/records_test.go
Ctrl+C can be used safely now.
=> Do not record partial files

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature.yml
=> Sync label descriptions and issue templates

integration/basic_test.go, integration/findandmodify_test.go, internal/handlers/pg/pgdb/databases.go, internal/util/testutil/db.go, website/docs/diff.md
=> Allow `-` in database names

internal/handlers/pg/msg_listindexes.go, internal/handlers/tigris/msg_listindexes.go
There's an array inside the array by accident.
Also: should we send some message in response that this command is only a stub and the output is not relevant becuase we don't support indexes at this moment?
=> Fix `listIndexes` stub

CONTRIBUTING.md, README.md, Taskfile.yml, cmd/envtool/envtool.go, website/docs/quickstart_guide/docker.md
So we all use the same modern Docker Compose.
=> Replace `docker-compose` with `docker compose`

internal/types/document_validation.go, internal/types/document_validation_test.go
It was wrong to use `types.Document.Get` in validation because `types.Document.Get` can't work with duplicate keys correctly.
Luckily, now `types.Document.Get` panics in case of duplicate keys, so with the help of dance tests, we were able to catch this problem.
In principle, in such cases, we should att unit tests to make sure that the code is covered.
=> Fix validation for documents with duplicate keys

Taskfile.yml, build/deps/centos7.Dockerfile, build/deps/debian11.Dockerfile, build/deps/ubi9.Dockerfile, build/deps/ubuntu2204.Dockerfile, docker-compose.yml
It was broken by switching runners to Ubuntu 22.04.
=> Fix `.deb`/`.rpm` package testing

internal/wire/op_msg.go, internal/wire/op_msg_test.go, internal/wire/wire_test.go
Sections of kind 0 should be considered first.
Closes #1632.
=> Fix parsing of `OP_MSG` packets with multiple sections

build/deps/tigris.Dockerfile, cmd/envtool/envtool.go, go.mod, go.sum, integration/go.mod, integration/go.sum, internal/handlers/tigris/msg_dbstats.go, internal/handlers/tigris/msg_dropdatabase.go, internal/handlers/tigris/msg_listdatabases.go, internal/handlers/tigris/tigrisdb/databases.go, internal/handlers/tigris/tigrisdb/tigrisdb_test.go
=> Bump Tigris deps

.github/RELEASE_CHECKLIST.md, .github/workflows/docker.yml, Taskfile.yml, internal/util/version/generate.go
Build and push all Docker images at once.
=> Simplify release procedure

.github/workflows/docker.yml, .github/workflows/integration.yml
Run integration tests on faster (paid) instances.
=> Use faster runner instances

internal/handlers/common/msg_listcommands.go
=> Add `findandmodify` to the `common.Commands` map

integration/query_bitwise_test.go
The problem was revealed after refactoring bitwise-related tests and more data test cases being added. This is what we already do in some other tests affected by the same reason.
Those tests will still run on CI.
=> Skip incompatible tests on `arm64`

.github/workflows/conform-pr.yml, .github/workflows/docker.yml, Taskfile.yml, build/nfpm.yaml, docker-compose.yml, internal/handlers/common/msg_listcommands.go, website/docs/flags.md
=> Minor cleanups

website/docusaurus.config.js
=> Fix links from docs to blog

internal/handlers/pg/pgdb/transactions.go, internal/handlers/tigris/tigrisdb/databases.go
Bumping `retriesMax` is a temporary workaround, not a real fix. But logging should improve diagnostics.
=> Retry transaction more times and log retries

cmd/ferretdb/main.go, ferretdb/ferretdb.go, ferretdb/ferretdb_test.go, integration/embedded_test.go, integration/setup/common.go, internal/clientconn/listener.go
Spotted while working on making tests faster.
=> Remove `ListenerOpts` from another `ListenerOpts`

Taskfile.yml, docker-compose.yml
If you run `task blog-dev`, it shows you that the Docusaurus website is running on 3000 port, which is not true, as for blogs we use 3001:
```
task blog-dev
task: [blog-dev] docker compose run --rm --service-ports docusaurus-blog start --host=0.0.0.0
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/
✔ Client
Compiled successfully in 6.89s
client (webpack 5.75.0) compiled successfully
```
This is because the docusaurs container internally runs the website on 3000 and we just forward ports externally.
I've simply changed internal port to 3001, to make it straightforward and don't create confusion:
```
task blog-dev
task: [blog-dev] docker compose run --rm --service-ports docusaurus-blog start --host=0.0.0.0 --port=3001
[INFO] …
```
=> Make proper port visible on blog development server

internal/handlers/pg/pgdb/transactions.go, internal/handlers/pg/pgdb/transactions_test.go
It hangs if `f` function panics.
=> Fix `InTransaction` helper's edge case

internal/handlers/pg/pgdb/query.go, internal/handlers/pg/pgdb/query_iterator.go, internal/handlers/tigris/tigrisdb/query_iterator.go, internal/util/iterator/close.go
It could be used to track both rows and transaction in a single iterator.
=> Add `iterator.WithClose` helper

README.md, docker-compose.yml, website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md, website/docs/quickstart_guide/docker.md
It is deprecated: https://docs.docker.com/compose/compose-file/compose-versioning/
=> Do not specify Docker Compose version

integration/query_comparison_compat_test.go, internal/handlers/pg/pgdb/query.go, internal/handlers/pg/pgdb/query_test.go, internal/handlers/tigris/tigrisdb/query.go, internal/handlers/tigris/tigrisdb/query_test.go
Closes #2114.
`$eq` should work correctly, the tests for Max and Min values were already there and I couldn't came up with any other corner cases that could potentially skip some data. As we don't validate types on backend, query will prefetch everything that's equal to underlying value, but the final type filtering is done by FerretDB.
`$ne` should work correctly as it does the type checking on the backend.
I've also changed the name of PR to `date` as that's how bson call it. If we prefer other naming like `datetime`, `time` or anything, feel free to edit it.
=> Pushdown `date` values

cmd/ferretdb/main_hana.go, cmd/ferretdb/main_tigris.go
=> Fix `hana` and `tigris` handlers initialization

internal/clientconn/conn.go
`os.Rename` fails when `/tmp` and `./tmp` are on different devices.
=> Fix traffic recording

internal/handlers/common/filter_iterator.go, internal/handlers/pg/msg_aggregate.go, internal/handlers/pg/msg_find.go, internal/handlers/pg/pgdb/query_iterator.go, internal/handlers/pg/pgdb/query_test.go, internal/handlers/tigris/msg_aggregate.go, internal/handlers/tigris/msg_find.go, internal/handlers/tigris/tigrisdb/query_iterator.go, internal/handlers/tigris/tigrisdb/query_test.go, internal/types/documents_iterator.go
=> Remove indexes from `DocumentsIterator`

internal/handlers/pg/msg_createindexes.go
=> Ignore `unique` index option for now

build/version/version.go, cmd/ferretdb/main.go, website/docs/telemetry.md
That's needed for environments like Civo.
=> Allow setting "package" variable with a testing flag

Taskfile.yml
=> Make it easier to use Docker-related Task targets

website/blog/_guide/YYYY-MM-DD.blog-template.md, website/blog/_guide/content-process.md, website/docs/contributing/writing-guide.md
It seems like `unlisted` feature wasn't release yet.
It is mentioned there: https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter
but not there: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter
Closes #2370.
=> Use `draft` instead of `unlisted`

.dockerignore, .github/workflows/packages.yml
=> Do not mark released binaries as dirty

README.md
When reading the README for the first time, I was left wondering what the SSPL was, and why it might be a problem, so this change merely links to the license in question, for ease of browsing and understanding: https://www.mongodb.com/licensing/server-side-public-license.
=> Update README.md to link to SSPL

cmd/envtool/envtool.go, integration/commands_administration_test.go, internal/clientconn/listener.go, internal/handlers/pg/pgdb/transactions.go, internal/handlers/tigris/tigrisdb/databases.go, internal/util/ctxutil/ctxutil.go, internal/util/ctxutil/ctxutil_test.go, website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
Closes #1720.
I have added ctxutil.SleepWithJitter based on https://aws.amazon.com/ru/blogs/architecture/exponential-backoff-and-jitter/ (FullJitter).
I did not complete all tasks in the issue for the following reason:
- time.Sleep is not used
- context.WithTimeout is only used for actual timeout from what I'm reading. It does not make sense to add jitter to context timeouts if FerretDB does not retry something based on the context timing out.
- ctxutil.Sleep has been replaced with a version that adds jitter with one exception: reporter.Run has a reportInternal duration that has no need for jitter.
- All other ctxutil.Sleeps where located in for loops where the intention is clear that FerretDB is retrying some task. Adding jitter makes sense in these cases.
For the three unit tests I have …
=> Use exponential backoff with jitter

.github/workflows/debug.yml, .github/workflows/docs-preview.yml, .github/workflows/security.yml, CHANGELOG.md, website/docs/basic-operations/delete.md, website/docs/basic-operations/read.md, website/docs/basic-operations/update.md, website/docs/operators/query/logical-operators.md, website/docs/operators/update/array-update-operators.md
And show how to get docs preview URL.
=> Remove a few double spaces

website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
=> Update blog post on Using FerretDB with Studio3T

cmd/envtool/envtool.go
=> Handle `envtool` panic on timeout

.github/workflows/integration.yml, .golangci-new.yml, .markdownlint.yml, Taskfile.yml, integration/.golangci-new.yml
Closes #1301.
In this PR:
- Change permissions only for linux.
- Run yaml formatter as part of `fmt` task.
- In this PR, I also run yaml formatter to format our current yaml files.
=> Small addition to YAML formatter usage

internal/handlers/common/msg_hostinfo.go
Closes #2500.
Add identifying Arch Linux version in `hostInfo` command.
Most of Linux distributions contain `/etc/os-release` - the file used by FerretDB for `hostInfo` command.
However, Arch has `/etc/arch-release` instead of it. To keep functionality for most of Linux distributions the special Arch condition has been added.
=> Add identifying Arch Linux version in `hostInfo` command

tools/checkdocs/checkdocs.go, tools/checkdocs/checkdocs_test.go
=> Minor cleanup of blog post linter for slug

internal/handlers/common/msg_hostinfo.go, internal/handlers/common/parse_osrelease.go
Closes #2500.
Based on @AlekSi 's comment:
Update identifying Linux version in `hostInfo` comand - based on `/usr/lib/os-release` instead of `/usr/lib/arch-release`.
=> Handle absent `os-release` file

integration/Taskfile.yml, internal/handlers/common/params.go, internal/types/document.go, internal/util/iterator/count.go, internal/util/iterator/values.go, internal/util/must/must.go, tools/Taskfile.yml
=> Do various small cleanups

integration/aggregate_documents_compat_test.go, integration/findandmodify_compat_test.go, integration/query_compat_test.go, internal/handlers/common/sort.go
=> Fix `$` path errors for sort

internal/handlers/common/msg_hostinfo.go, internal/handlers/common/parse_osrelease.go, internal/handlers/common/parse_osrelease_test.go
Closes #2500 .
Add  in parseOSRelease support for:
- unquoting values
- dealing with more than one `=` in values - there should be only one delimiter per line
=> Improve handling of `os-release` files

Taskfile.yml, cmd/envtool/envtool.go
Closes #2550 .
Added `envtool setup` [kong](https://github.com/alecthomas/kong) subcommand.
=> Add proper CLI to `envtool` - `envtool setup`  subcommand

internal/handlers/pg/pg.go, internal/handlers/pg/pgdb/pgdb_test.go, internal/handlers/pg/pgdb/pool.go, internal/handlers/registry/hana.go, internal/handlers/registry/tigris.go, website/docs/security.md, website/docs/understanding-ferretdb.md
Allow more locales, improve error messages and documentation.
=> Relax PostgreSQL connection checks

cmd/envtool/envtool.go, cmd/envtool/envtool_test.go
=> Simplify `envtool shell` subcommands

internal/handlers/common/count.go
=> Fix `count`'s `query` parameter

integration/commands_administration_test.go, internal/handlers/common/aggregations/stages/collstats.go, internal/handlers/common/serverstatus.go, internal/handlers/pg/msg_aggregate.go, internal/handlers/pg/msg_collstats.go, internal/handlers/pg/msg_dbstats.go, internal/handlers/pg/msg_explain.go, internal/handlers/pg/pgdb/stats.go, internal/handlers/tigris/msg_aggregate.go, internal/handlers/tigris/msg_collstats.go, internal/handlers/tigris/msg_datasize.go, internal/handlers/tigris/msg_explain.go
To make them work for large databases and collections.
=> Return `int64` values for `dbStats` and `collStats`

.github/workflows/integration.yml, integration/Taskfile.yml, integration/setup/listener.go, integration/setup/setup.go, integration/shareddata/composites.go, integration/shareddata/scalars.go
=> Include Hana in integration tests

internal/clientconn/conn.go, internal/handlers/pg/msg_insert.go, internal/handlers/tigris/msg_insert.go
=> Remove the need to call `DeepCopy` in some places

.golangci-new.yml, integration/.golangci-new.yml, internal/handlers/pg/pgdb/pool.go, internal/util/lazyerrors/lazyerrors.go, internal/util/lazyerrors/lazyerrors_test.go
=> Clean-up `lazyerrors`, use them in more places

.golangci-new.yml, internal/handlers/pg/msg_explain.go, internal/handlers/sqlite/cmd_query.go, internal/handlers/sqlite/msg_createindexes.go, internal/handlers/sqlite/msg_explain.go, internal/handlers/sqlite/msg_hello.go, internal/handlers/sqlite/msg_ismaster.go, internal/util/testutil/db.go, internal/util/testutil/path.go
=> Implement a few command stubs

integration/findandmodify_compat_test.go
Closes #2736.
Previous PR https://github.com/FerretDB/FerretDB/pull/2779 actually did not fix it for MongoDB 6.0.6. See https://github.com/FerretDB/FerretDB/pull/2727.
* Any `$` prefixed keys are valid in MongoDB 6.0.6. Let's remove those tests, we have diff documented in https://github.com/FerretDB/FerretDB/blob/main/website/docs/diff.md?plain=1#L19.
* Diff test created in https://github.com/FerretDB/dance/pull/466
=> Remove `findAndModify` integration tests with `$` prefixed key for MongoDB 6.0.6 compatibility

.golangci-new.yml, cmd/envtool/envtool_test.go, integration/setup/setup.go, integration/setup/setup_compat.go, internal/handlers/pg/pgdb/pgdb_test.go, internal/handlers/tigris/tigrisdb/query_test.go, internal/handlers/tigris/tigrisdb/tigrisdb_test.go, internal/util/telemetry/telemetry_test.go, internal/util/testutil/testutil.go
=> Make `testutil.Logger` easier to use

integration/commands_freemonitoring_test.go
=> Fix free monitoring tests for MongoDB 6.0.6

.github/codecov.yml, .github/workflows/go.yml, Taskfile.yml, cmd/envtool/envtool.go, cmd/envtool/envtool_test.go, cmd/envtool/tests.go, cmd/envtool/tests_test.go
This PR improves, simplifies, and refactors sharding logic, and hooks it into CI.
Branch protection rules should be updated, hence https://github.com/FerretDB/FerretDB/labels/do%20not%20merge.
=> Shard integration tests

build/.textlintrc, internal/bson/document.go, website/blog/2022-08-23-open-source-is-in-danger.md, website/blog/2023-01-04-ferretdb-beta-version-authentication.md, website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
So we don't document `–handler` or `—handler` instead of `--handler`.
=> Add textlint rules for en dashes and em dashes

integration/aggregate_documents_compat_test.go, internal/handlers/common/add_fields_iterator.go, internal/handlers/common/aggregations/stages/add_fields.go, internal/handlers/common/aggregations/stages/group.go, internal/handlers/common/aggregations/stages/set.go, internal/handlers/common/aggregations/stages/stages.go, internal/handlers/common/validate.go, internal/handlers/commonerrors/error.go, internal/handlers/commonerrors/errorcode_string.go
Closes #2590 .
Implemented [$addFields](https://www.mongodb.com/docs/manual/reference/operator/aggregation/addFields/) / [$set ](https://www.mongodb.com/docs/manual/reference/operator/aggregation/set/)aggregation pipeline.
I have added support only for literal values.  Expressions will be implemented as part of https://github.com/FerretDB/FerretDB/issues/1413
=> Implement simple `$addFields/$set` aggregation pipeline stages

internal/handlers/common/find.go, internal/handlers/commonparams/extract_params.go, internal/handlers/commonparams/extract_params_test.go
The description of the `unimplemented-non-default` tag was updated but usage was not.
=> Fix `unimplemented-non-default` tag usages

website/blog/2023-06-19-ferretdb-v-1-4-0-new-release.md, website/static/img/blog/ferretdb-v1.4.0.jpg
=> Add blogpost on FerretDB v1.4.0

integration/commands_diagnostic_test.go, internal/handlers/common/aggregations/stages/group.go
All TLS parameters are now a part of URI.
Closes #1759.
=> Unskip test that passes now

website/docs/contributing/index.md
=> Fix Github link for Dance repository

internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/hana/hana.go, internal/handlers/handlers.go, internal/handlers/pg/pg.go, internal/handlers/sqlite/sqlite.go, internal/handlers/tigris/tigris.go
=> Add handler's metrics registration

cmd/envtool/envtool.go, ferretdb/ferretdb.go, integration/setup/client.go, integration/setup/listener.go, integration/setup/setup.go, integration/setup/setup_compat.go, internal/clientconn/conn.go, internal/clientconn/listener.go, internal/handlers/common/count_iterator.go, internal/handlers/commoncommands/msg_listcommands.go, internal/util/iterator/func.go, internal/util/iterator/slice.go, internal/util/iterator/values.go, internal/util/iterator/with_close.go, internal/util/telemetry/reporter.go
To make the next PR smaller and focused.
=> Clean-up some code and comments

internal/handlers/sjson/sjson_test.go, internal/wire/record.go, internal/wire/wire_test.go
Closes #2940.
Refs #1636.
Please do not recommend `rm -fr tmp` as a workaround after that.
=> Do not break fuzzing initialization

integration/helpers.go, integration/setup/client.go, integration/setup/listener.go, integration/setup/setup.go, integration/setup/setup_compat.go, integration/setup/test_helpers.go, internal/bson/bson_test.go, internal/handlers/pg/pgdb/pgdb_test.go, internal/handlers/sjson/sjson_test.go, internal/util/testutil/db.go, internal/util/testutil/dump.go, internal/util/testutil/equal.go, internal/util/testutil/hexdump.go, internal/util/testutil/path.go, internal/util/testutil/pg.go, internal/util/testutil/testtb/tb.go, internal/util/testutil/testutil.go, internal/util/testutil/xfail.go, internal/wire/wire_test.go
That removes the import cycle in the next PR.
=> Move `testutil.TB` to `testtb.TB`

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, Taskfile.yml, integration/setup/setup_compat.go, internal/handlers/sjson/sjson_test.go, internal/wire/wire_test.go
To make the PR template match reality.
For everyone to review.
=> Make `task all` run only unit tests

internal/backends/backend.go, internal/backends/collection.go, internal/backends/database.go, internal/backends/doc.go, internal/backends/error.go, internal/backends/error_test.go
=> Fix error checking in backend contracts

internal/handlers/common/aggregations/aggregations.go, internal/handlers/common/aggregations/stages/add_fields.go, internal/handlers/common/aggregations/stages/collstats.go, internal/handlers/common/aggregations/stages/count.go, internal/handlers/common/aggregations/stages/group.go, internal/handlers/common/aggregations/stages/limit.go, internal/handlers/common/aggregations/stages/match.go, internal/handlers/common/aggregations/stages/project.go, internal/handlers/common/aggregations/stages/set.go, internal/handlers/common/aggregations/stages/skip.go, internal/handlers/common/aggregations/stages/sort.go, internal/handlers/common/aggregations/stages/unset.go, internal/handlers/common/aggregations/stages/unwind.go, internal/handlers/pg/msg_aggregate.go, internal/handlers/pg/pgdb/stats.go
Closes #2423.
Just the easy part of removing `Type()` interface. The remaining part of moving `$collStats` specific logic out from `msg_aggregation.go` will be done part of task implementation.
Keep the issue open after this PR is merged.
=> Remove `Type()` interface from aggregation stage

internal/handlers/common/count.go
=> Ignore `count.fields` argument

.golangci.yml, integration/.golangci-new.yml, integration/.golangci.yml, integration/delete_test.go
We use values in all other tests.
=> Do not import `commonerrors` in tests

Taskfile.yml, integration/Taskfile.yml, integration/setup/listener.go, integration/setup/setup.go, integration/setup/startup.go, internal/backends/sqlite/metadata/pool/db.go, internal/backends/sqlite/metadata/pool/pool.go, internal/backends/sqlite/metadata/pool/pool_test.go, internal/backends/sqlite/metadata/pool/uri.go, internal/backends/sqlite/metadata/pool/uri_test.go
=> Allow to change SQLite URI in tests

Taskfile.yml, tools/checkdocs/checkdocs.go, tools/checkdocs/checkdocs_test.go, website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md, website/blog/_guide/content-process.md, website/docs/contributing/writing-guide.md
That PR simplifies the linter's code to make it easier to add new checks.
It also fixes the checking of tags with spaces.
Closes #3078.
=> Simplify `checkdocs` linter

integration/query_test.go
- `query_test.go`
Some of the tests inside this file are unstable, I've appended the file to the scope of #3172.
Other query tests seem to pass.
Closes #3131.
=> Make `query` integration tests pass for SQLite

integration/getmore_test.go, integration/indexes_command_compat_test.go, integration/indexes_compat_test.go
- `getmore_test.go`
- `indexes_command_compat_test.go`
Closes #3131.
=> Make `getMore` integration tests pass for SQLite

integration/insert_command_test.go, integration/update_compat_test.go
- `update_compat_test.go`
`TestUpdateCompat` fails for some subtests and passes for other subtests, it seems impossible to catch failure correctly without overcomplicating.
Closes #3131.
=> Make `update` integration tests pass for SQLite

integration/aggregate_variables_compat_test.go
=> Add tests for `$$ROOT`

internal/backends/sqlite/metadata/registry.go, internal/util/fsql/metrics.go
Added missing metrics for the `*sql.DB` pool statistics. 
Closes #2909.
=> Add more metrics for `*sql.DB`

.github/settings.yml, Taskfile.yml, build/certs/Makefile, build/deps/mongo6.Dockerfile, build/mongod.conf, build/mongodb.conf, build/mongodb_secured.conf, cmd/envtool/envtool.go, docker-compose.yml, integration/Taskfile.yml, integration/commands_administration_test.go, internal/util/ctxutil/ctxutil.go, internal/util/ctxutil/ctxutil_test.go
=> Tweak MongoDB initialization process

integration/commands_administration_test.go, integration/commands_freemonitoring_test.go
Closes #{issue_number}.
Free monitoring cannot be enabled anymore https://www.mongodb.com/docs/manual/reference/command/setFreeMonitoring/
=> Skip tests for `enable` `setFreeMonitoring` for MongoDB

integration/update_compat_test.go, internal/handlers/sqlite/msg_update.go
Closes #3183.
The approach with `WriteError` is the same as in `msg_insert` for consistency purposes.
=> Return correct response if unique index violation happened on SQLite backend

CHANGELOG.md, CONTRIBUTING.md, internal/bson/bson_test.go, internal/handlers/pg/msg_aggregate.go, internal/handlers/pg/msg_find.go
=> Use consistent spelling

internal/clientconn/conn.go, internal/clientconn/conninfo/conn_info.go, internal/clientconn/conninfo/conn_info_test.go
=> Remove the need to close `conninfo`

internal/backends/sqlite/metadata/registry.go
Closes #{issue_number}.
Switch the order of code so that sqlite registry has below order
```
func ExportedAFunc() ...
func unexportedAFunc() ...
func ExportedBFunc() ...
func unexportedbFunc() ..
```
=> Reorder codebase in SQLite registry

.github/workflows/call-test-integration.yml, .github/workflows/go-cron.yml, .github/workflows/go-integration.yml, .github/workflows/go.yml, Taskfile.yml, internal/backends/backend.go, internal/backends/collection.go, internal/backends/database.go, internal/backends/doc.go, internal/handlers/sqlite/sqlite.go
=> Run new PostgreSQL backend tests

internal/backends/sqlite/metadata/pool/pool_test.go, internal/backends/sqlite/metadata/registry_test.go
Prevent one kind of tests failure.
=> Tweak SQLite backend tests

.github/workflows/packages.yml, cmd/envtool/envtool.go, cmd/envtool/tests.go
The logic condition was wrong, and the error was hidden.
=> Fix running a subset of tests

.github/settings.yml, go.mod, integration/go.mod, internal/backends/collection.go, internal/backends/collection_test.go, internal/backends/decorators/dummy/collection.go, internal/backends/decorators/oplog/collection.go, internal/backends/hana/collection.go, internal/backends/helpers_test.go, internal/backends/postgresql/collection.go, internal/backends/sqlite/collection.go, tools/go.mod, tools/golangci/go.mod
=> Add stubs for `Collection.Compact`

integration/commands_diagnostic_test.go, internal/backends/sqlite/metadata/pool/pool_test.go, internal/backends/sqlite/metadata/registry_test.go, internal/util/testutil/teststress/stress.go
They pass now on machines with many CPUs.
=> Fix stress tests

cmd/ferretdb/main.go, internal/backends/collection.go, internal/backends/database.go, internal/backends/postgresql/collection.go, internal/backends/sqlite/collection.go, internal/handlers/common/find.go, internal/handlers/pg/msg_serverstatus.go, internal/handlers/sqlite/msg_collstats.go, internal/handlers/sqlite/msg_create.go, website/docs/reference/supported-commands.md
=> Add TODOs for capped collections

ferretdb/ferretdb.go
=> Improve embedded package documentation

integration/pushdown.go, integration/query_comparison_compat_test.go, integration/query_compat_test.go, integration/query_projection_compat_test.go, integration/query_test.go, internal/backends/sqlite/collection.go
It is an ad-hoc filter for an important use-case that covers only the `_id` field because it can't be an array.
Refs #3235.
Closes FerretDB/dance#625.
=> Add filter pushdown for `_id: <string>` for SQLite

integration/benchmarks_test.go, internal/types/document.go, internal/types/document_test.go, internal/types/types.go
We don't want to fully remove or refactor that code just yet (that's #2412), but we can make it quicker… quickly.
```
task: [bench-postgresql] ../bin/benchstat old-postgresql.txt new-postgresql.txt
goos: darwin
goarch: arm64
pkg: github.com/FerretDB/FerretDB/integration
│ old-postgresql.txt │          new-postgresql.txt          │
│       sec/op       │    sec/op     vs base                │
Find/SmallDocuments/Docs1000/7dc4/Int32ID-10                      2.237m ±  6%   2.102m ± 14%        ~ (p=0.165 n=10)
Find/SmallDocuments/Docs1000/7dc4/Int32One-10                     2.337m ±  6%   1.902m ± 11%  -18.62% (p=0.000 n=10)
Find/SmallDocuments/Docs1000/7dc4/Int32Many-10                    7.425m ±  1%   7.161m ±  1%   -3.55% (p=0.000 n=10) …
```
=> Optimize detection of duplicate fields

.github/settings.yml, CHANGELOG.md, Taskfile.yml, cmd/envtool/envtool.go, cmd/envtool/envtool_test.go, cmd/envtool/error.tmpl, cmd/envtool/tests_test.go
Also, remove https://github.com/FerretDB/FerretDB/labels/hacktoberfest until the next year.
=> Make tests stable on CI

cmd/ferretdb/main.go, website/docs/configuration/flags.md
To resolve https://github.com/FerretDB/FerretDB/issues/3517
I am brand new to Go and just want to be helpful, so I hope that I don't end up creating more work for your team to review this.
=> Add option to disable `--debug-addr`.

cmd/ferretdb/main.go, website/docs/configuration/flags.md
=> Allow usage without state dir

cmd/ferretdb/main.go, website/docs/configuration/flags.md
=> Use `-` in addition to the empty string

cmd/envtool/envtool.go, cmd/envtool/testdata/panic_test.go, cmd/envtool/tests.go, cmd/envtool/tests_test.go
Stack traces are no longer hidden.
=> Handle panicking tests

internal/backends/postgresql/metadata/registry.go, internal/backends/postgresql/metadata/registry_test.go, internal/util/testutil/postgresql.go
So default schemas like `public` could be used.
=> Allow the usage of existing PostgreSQL schema

README.md, internal/backends/postgresql/collection.go, internal/backends/sqlite/collection.go, internal/handlers/sqlite/msg_insert.go, website/blog/2023-11-16-guide-to-migrating-mongodb-ferretdb.md
=> Add TODOs and fix URLs

internal/backends/validation.go
That will change once we have authorization.
=> Allow `system.` prefix for collections for now

integration/commands_diagnostic_test.go, internal/handler/msg_validate.go, website/docs/reference/supported-commands.md
=> Improve `validate` diagnostic command

build/version/version.go, cmd/ferretdb/main_postgresql.go, cmd/ferretdb/main_sqlite.go, internal/handler/registry/postgresql.go, internal/handler/registry/registry_test.go, internal/handler/registry/sqlite.go
**Requirement**:  We should allow building FerretDB without PostgreSQL and/or SQLite backend with `ferretdb_no_postgresql` and `ferretdb_no_sqlite` build tags. Both should be absent in official builds.
I have added the relevant build tags in postgres & sqlite handler and registry files. The corresponding test `TestDeps` is skipped in the `main` branch. I have added placeholders for testing the above build tag changes. We can fix these once the `TestDeps` is fixed.
1. Add required build tags in `BUILD_TAGS` in `Taskfile.yml`.
2. Build using `task build-host`.
3. Check the compiled handlers using `bin/ferretdb -h`.
1. Build without Postgresql
Build tags given
Postgres handler is absent.
2. Build without Sqlite
Build tags given
Sqlite handler is absent.
Closes #3629
=> Allow building without PostgreSQL or SQLite backend

internal/handler/common/count.go, internal/handler/common/delete_params.go, internal/handler/common/distinct.go, internal/handler/common/find.go, internal/handler/common/findandmodify.go, internal/handler/common/insert.go, internal/handler/common/update_params.go
To make proxy-diff mode usable again.
=> Ignore `$clusterTime`

integration/query_compat_test.go, internal/handler/common/sort.go
=> Disallow `$natural` in compound sort

internal/backends/postgresql/metadata/pool/pool.go, internal/backends/postgresql/metadata/registry.go, internal/clientconn/conninfo/conn_info.go
=> Allow bypassing authentication

internal/handler/msg_find.go
=> Add missing logging parameter

integration/findandmodify_compat_test.go, integration/update_field_compat_test.go
=> Add `upsert` tests

Taskfile.yml, cmd/ferretdb/main.go, integration/setup/listener.go, internal/backends/decorators/oplog/backend.go, internal/backends/decorators/oplog/collection.go, internal/backends/postgresql/collection.go, internal/backends/sqlite/collection.go, internal/handler/handler.go, internal/handler/msg_create.go, internal/handler/registry/hana.go, internal/handler/registry/mysql.go, internal/handler/registry/postgresql.go, internal/handler/registry/registry.go, internal/handler/registry/sqlite.go
OpLog functionality does nothing if `local.oplog.rs` collection is not created. The user is expected to create it manually.
Closes #76.
=> Enable OpLog and tailable cursors

internal/handler/msg_aggregate.go
=> Fix clean-up on `aggregate` errors

integration/cursors/getmore_test.go
=> Add more cursor tests

.golangci-new.yml, .golangci.yml
=> Forbid `bson.E/D/M/A`, except integration tests

integration/setup/setup.go, integration/setup/setup_compat.go, integration/users/create_user_test.go, integration/users/drop_all_users_from_database_test.go, integration/users/drop_user_test.go
Removes the need to do it in every test.
=> Drop test users on cleanup

internal/handler/msg_getmore.go
=> Cleanup `awaitData` tailable cursor

internal/backends/mysql/metadata/pool/uri.go, internal/backends/mysql/metadata/registry_test.go
Resolves the issue causing MySQL backend's registry_test to fail; alternate MySQL errors
Closes #3413.
=> Disallow native passwords for MySQL

build/docker/all-in-one.Dockerfile, build/docker/development.Dockerfile, build/docker/production.Dockerfile
Download Go modules in a separate host-native stage.
Switch base images to upstream's `golang`.
Closes #2170.
=> Speed-up Docker builds

.github/mergify.yml, integration/users/create_user_test.go, integration/users/drop_all_users_from_database_test.go, integration/users/drop_user_test.go, internal/backends/mysql/metadata/pool/pool.go, internal/backends/mysql/metadata/registry.go, internal/backends/postgresql/metadata/registry.go, internal/clientconn/conninfo/conn_info.go, internal/handler/handler.go, internal/handler/sjson/sjson_marshal_unmarshal_test.go, internal/util/password/plain.go, internal/util/password/plain_test.go
It is required for SCRAM anyway.
Closes #3938.
=> Use PBKDF2 for storing `PLAIN` passwords

internal/handler/common/count.go, internal/handler/common/delete_params.go, internal/handler/common/distinct.go, internal/handler/common/find.go, internal/handler/common/findandmodify.go, internal/handler/common/update_params.go, tools/checkcomments/testdata/testdata.go
Some drivers will attach a `$readPreference` document when connecting to a replica set, see [here](https://github.com/FerretDB/dance/actions/runs/7609512189/job/20720911668?pr=738#step:8:2466) and [here](https://github.com/FerretDB/dance/actions/runs/7615410166/job/20740339032?pr=738#step:8:200) for failures. We should ignore this field altogether.
=> Ignore `$readPreference` field

internal/bson2/raw_array.go, internal/bson2/raw_document.go, internal/bson2/slog.go
To simplify the transition from `bson`+`types` to `bson2`.
=> Add `bson2` helpers for conversions and logging

internal/bson2/bson2.go, internal/bson2/document.go, internal/bson2/document_test.go, internal/bson2/raw_array.go, internal/bson2/raw_document.go, internal/bson2/slog.go
It will be used during the decoding of OP_MSG sections of kind 1.
=> Add helper for decoding document sequences

internal/handler/cmd_query.go, internal/handler/common/ismaster.go, internal/handler/sjson/sjson_test.go, internal/wire/msg_body.go, internal/wire/op_msg.go, internal/wire/op_msg_test.go, internal/wire/op_query.go, internal/wire/op_query_test.go, internal/wire/op_reply.go, internal/wire/op_reply_test.go, internal/wire/wire_test.go
That would allow us to avoid extra copying in the future.
=> Use `bson2` package for wire queries and replies

internal/handler/msg_createuser.go, internal/handler/msg_usersinfo.go, website/docs/reference/supported-commands.md
Both TODO does not seem to be related to speculative authenticate :thinking:, so I created issues for them. Let me know if I'm wrong.
One is about supporting `filter` in `usersInfo` command https://github.com/FerretDB/FerretDB/issues/4141, another is creating user for `$external` database https://github.com/FerretDB/FerretDB/issues/4142.
Closes #3777.
=> Cleanup TODO for speculative authenticate

internal/backends/mysql/collection.go
=> Fix MySQL collection stats

integration/users/connection_test.go, internal/backends/mysql/metadata/registry.go, internal/backends/postgresql/metadata/registry.go, internal/clientconn/conninfo/conn_info.go, internal/handler/authenticate.go, internal/handler/msg_logout.go, internal/handler/msg_saslstart.go
I found a bug related to enforcing new authentication, see added test.
Closes #1877.
=> Fix PLAIN mechanism authentication incorrectly working

internal/bson2/array.go, internal/bson2/document.go, internal/bson2/logging.go, internal/bson2/logging_test.go, internal/bson2/raw_array.go, internal/bson2/raw_document.go, internal/clientconn/conn.go, internal/wire/msg_body.go, internal/wire/op_msg.go, internal/wire/op_query.go, internal/wire/op_reply.go, internal/wire/wire_test.go, website/docs/configuration/operation-modes.md, website/docs/migration/premigration-testing.md
=> Do not use the flow style in the diff output

website/docs/reference/supported-commands.md
=> Remove some closed issues from documentation

Taskfile.yml, go.mod, go.sum, integration/go.mod, integration/go.sum, tools/go.mod, tools/go.sum
Fixes a potential security issue.
Also, downgrade `vuln` to work around its problem.
=> Bump `pgx`

build/ferretdb/production.Dockerfile
Fun fact: surprisingly, I found the answer in the only book about Docker I own 😄 
In this change, in the Dockerfile `state` dir is created explicitly, and in the final stage, its ownership is assigned to the necessary user through `--chown` flag. This explicitly sets ownership, and even if a docker container would be run with an anonymous volume (e.g. through `docker run` without setting `-v` or `--mount`), the `ferretdb` user will have the necessary permission.
In case, volume is specified when starting the container, the specified volume will be used. 
E.g. something like `docker run -v ./state:/state my-ferretdb-image` would work without having those `mkdir` and `COPY`.
Closes #3992.
=> Use non-privileged `scratch` for production Docker images

Taskfile.yml, tools/Taskfile.yml, tools/checkcomments/checkcomments_test.go, tools/checkcomments/client.go
=> Move tools cache directory

.github/workflows/go.yml, CONTRIBUTING.md, Taskfile.yml, integration/Taskfile.yml, integration/setup/listener.go, integration/setup/setup.go, integration/setup/setup_compat.go, integration/shareddata_test.go, integration/users/connection_test.go
Simplifies `task env-data` logic.
=> Populate `env-data` for running `FerretDB`

Taskfile.yml, build/ferretdb/all-in-one.Dockerfile, build/ferretdb/development.Dockerfile, build/ferretdb/production.Dockerfile, cmd/ferretdb/main.go
Closes #4246.
Ping implementation will be done in #4364.
```
./bin/ferretdb --help
warning: GOCOVERDIR not set, no coverage data emitted
Usage: ferretdb <command> [flags]
Flags:
-h, --help                                                   Show context-sensitive help.
--version                                                Print version to stdout and exit.
--handler="postgresql"                                   Backend handler: 'postgresql', 'sqlite', 'hana', 'mysql' ($FERRETDB_HANDLER).
--mode="normal"                                          Operation mode: 'normal', 'proxy', 'diff-normal', 'diff-proxy' ($FERRETDB_MODE).
--state-dir="."                                          Process state directory ($FERRETDB_STATE_DIR).
--repl-set-name="" …
```
=> Add stub for the Docker healthcheck

.github/workflows/_integration.yml, .github/workflows/go.yml
Workaround for codecov/codecov-cli#460.
=> Fix codecov CLI version

integration/setup/listener.go, internal/handler/cmd_query.go, internal/handler/msg_saslstart.go
We should use the database name as part of authentication. For example, `db1.user` and `db2.user` are two different users despite the same name. If `db1.user` user should have an access right to `db2` or other databases, it is assigned via authorization roles. https://www.mongodb.com/docs/manual/core/security-users/#authentication-database
Closes #4392.
=> Check database name for authentication

internal/util/ctxutil/sigterm_test.go
I was debugging a problem that did not exist. But hey, at least there are tests now. 😆
=> Add tests for `ctxutil.Sigterm`

cmd/envtool/tests.go, integration/aggregate_documents_compat_test.go, integration/aggregate_documents_test.go, integration/aggregate_stats_compat_test.go, integration/aggregate_stats_test.go, integration/diff_08_names_test.go, integration/setup/client.go, integration/setup/startup.go
Plus, don't run some subtests in parallel (based on Otel traces analyses).
=> Stop Otel exporter gracefully in `envtool`

internal/bson/decode.go, tools/checkswitch/checkswitch.go, tools/checkswitch/testdata/testdata.go
=> Use single definition of order for `checkswitch`

internal/types/array.go, internal/types/binary.go, internal/types/document.go, internal/types/logging.go, internal/types/logging_test.go, internal/types/null.go, internal/types/object_id.go, internal/types/regex.go, internal/types/timestamp.go
It will be used by logger in
* https://github.com/FerretDB/FerretDB/pull/4470/files#diff-6ca503e8ccb89677a82fa7b0b9f4d187b8f5ef8ac15622dd9f365b88e058b622R67
* https://github.com/FerretDB/FerretDB/pull/4470/files#diff-6ca503e8ccb89677a82fa7b0b9f4d187b8f5ef8ac15622dd9f365b88e058b622R67
* https://github.com/FerretDB/FerretDB/pull/4462/files#diff-beab5e5a6ad47631f2f20fadadb143272b0380767d7b3e4109fccb5655b16f39R378
Closes #4013.
=> Implement `slog.LogValuer` interface for `types` package

integration/commands_administration_test.go
The filter input to `listDatabases` test cases contain duplicate field `name`. When we move on to using `github.com/FerretDB/wire/wirebson` package, only the first field is fetched from a document if there are duplicate field names. 
Closes FerretDB/engineering#179.
=> Update `listDatabases` integration test filter input

website/docs/telemetry.md, website/versioned_docs/version-v1.21/telemetry.md, website/versioned_docs/version-v1.22/telemetry.md, website/versioned_docs/version-v1.23/telemetry.md
We never collected IP addresses, but that missing "not" is embarrassing.
=> Fix critical typo in telemetry documentation

internal/handler/common/count.go, internal/handler/common/delete_params.go, internal/handler/common/distinct.go, internal/handler/common/explain.go, internal/handler/common/find.go, internal/handler/common/findandmodify.go, internal/handler/common/insert.go, internal/handler/common/update_params.go
Closes #3121.
No test added, I think this is something better tested with relevant driver in dance.
The test script https://github.com/FerretDB/FerretDB/pull/4344 contains unimplemented CollMod command which causes fail after this fix.
=> Ignore Stable API fields

build/ferretdb/all-in-one.Dockerfile, build/ferretdb/development.Dockerfile, build/ferretdb/production.Dockerfile
A Dockerfile `HEALTHCHECK` instruction accepts either shell or exec array form for `CMD`, as mentioned in <https://docs.docker.com/reference/dockerfile/#healthcheck>:
> The command after the `CMD` keyword can be either a shell command (e.g. `HEALTHCHECK CMD /bin/check-running`) or an exec array (as with other Dockerfile commands; see e.g. `ENTRYPOINT` for details).
By using a shell command the healthcheck is run in the containers shell, which fails if there is none.
I rewrote all Dockerfiles' HEALTHCHECK CMD as an exec array, as `production.Dockerfile` builds an image without `/bin/sh`, making `dockerd` log multiple messages each second:
```
Aug 22 03:06:16 host dockerd[3578693]: time="2024-08-22T03:06:16.000432331+02:00" level=error msg="stream copy error: reading from a closed fifo"
Aug …
```
=> Fix Docker's `HEALTHCHECK` in production image

internal/handler/cmd_query.go
Duplicate field `saslSupportedMechs` was set on `hello` op query upon `speculativeAuthenticate`.
Closes #4065.
=> Fix duplicate field on `hello` op query

README.md, website/docs/understanding-ferretdb.md, website/versioned_docs/version-v1.22/understanding-ferretdb.md, website/versioned_docs/version-v1.23/understanding-ferretdb.md, website/versioned_docs/version-v1.24/understanding-ferretdb.md
If I undertstand correctly, GitHub's mermaid doesn't support `\n` as EOL, but `<br>` is used in mermaid's docs and works, see [here](https://mermaid.js.org/syntax/examples.html#larger-flowchart-with-some-styling). On docusaurus, `\n` works well, so I haven't touched it.
Before:
After:
=> Fix new lines in README's mermaid diagram

ferretdb/ferretdb.go, ferretdb/ferretdb_test.go, internal/util/testutil/logging.go
=> Make embeddable package logging configurable

website/docs/migration/diff.md
https://docs.ferretdb.io/migration/
=> Move comment in docs to fix DocCard

.github/ISSUE_TEMPLATE/config.yml, README.md, website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md, website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md, website/blog/2024-04-29-deploy-ferretdb-in-kubernetes-using-kubedb-managed-postgres.md, website/docs/introduction.md, website/docusaurus.config-blog.js, website/docusaurus.config.js, website/versioned_docs/version-v1.24/main.md
See:
- https://slack.ferretdb.io/
- https://github.com/FerretDB/slack
Please avoid using join.slack.com/XXX from now on.
---
This pull request updates various references to the Slack chat URL across multiple documentation files and configuration files. The new URL is `https://slack.ferretdb.io/`.
The most important changes include:
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L113-R113): Updated the Slack chat URL for quick questions.
* [`website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md`](diffhunk://#diff-cbc6f7db44137d4a9177a4ce4733f01d4c7cdd89a58db278f1b141736513f2d0L46-R46): Updated the Slack chat URL for raising questions or concerns.
* …
=> Update URL to join Slack

.github/workflows/_integration.yml
=> Use GitHub-hosted CI runners

tools/definedockertag/main.go, tools/definedockertag/main_test.go
Development (non-release) image that tracks the `main` branch with non-development (no race detector, etc) build inside. Mainly for tracking performance per commit, not per release.
Closes FerretDB/dance#1154.
=> Make production builds of the `main` branch

cmd/ferretdb/main.go, website/docs/configuration/flags.md
```
Usage: ferretdb <command> [flags]
Flags:
-h, --help       Show context-sensitive help.
--version    Print version to stdout and exit.
PostgreSQL
--postgresql-url="postgres://127.0.0.1:5432/postgres"    PostgreSQL URL ($FERRETDB_POSTGRESQL_URL).
Interfaces
--listen-addr="127.0.0.1:27017"    Listen TCP address for MongoDB protocol ($FERRETDB_LISTEN_ADDR).
--listen-unix=""                   Listen Unix domain socket path for MongoDB protocol ($FERRETDB_LISTEN_UNIX).
--listen-tls=""                    Listen TLS address for MongoDB protocol ($FERRETDB_LISTEN_TLS).
--listen-tls-cert-file=""          TLS cert file path ($FERRETDB_LISTEN_TLS_CERT_FILE).
--listen-tls-key-file=""           TLS key file path ($FERRETDB_LISTEN_TLS_KEY_FILE).
--listen-tls-ca-file=""            TLS CA file path …
```
=> Sync flags grouping with docs

internal/clientconn/conn.go, internal/handler/cmd_query.go, internal/handler/commands.go, internal/handler/middleware/middleware.go, internal/handler/middleware/observability.go
=> Handle `OP_QUERY` in middleware using interface

website/docusaurus.config.js, website/versioned_docs/version-v2.0/configuration/observability.md, website/versioned_docs/version-v2.0/installation/documentdb/deb.md, website/versioned_docs/version-v2.0/installation/documentdb/docker.md, website/versioned_docs/version-v2.0/installation/evaluation.md, website/versioned_docs/version-v2.0/installation/ferretdb/deb.md, website/versioned_docs/version-v2.0/installation/ferretdb/docker.md, website/versioned_docs/version-v2.0/installation/ferretdb/rpm.md
All that applies to 2.0.0, too.
Future PRs should do that themselves.
Closes #4921.
=> Backport documentation changes to v2.0

build/ferretdb/eval-dev.Dockerfile, build/ferretdb/evaluation/entrypoint.sh
Also always set `POSTGRES_DB` to `postgres`
Closes #4976.
=> Fix docker health check on evaluation image

internal/clientconn/conn.go, internal/clientconn/conninfo/conninfo.go, internal/dataapi/listener.go, internal/dataapi/server/server.go
Closes #5048.
Manually tested, checking no panic is raised for tracked resources.
=> Make `conninfo` a resource

build/.markdownlint.yml, website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx, website/blog/2023-10-31-mongodb-sorting-scalar.md, website/docs/configuration/flags.md, website/docs/guides/full-text-search.mdx, website/docs/guides/ttl-indexes.mdx, website/docs/guides/vector-search.mdx, website/versioned_docs/version-v1.24/configuration/flags.md, website/versioned_docs/version-v1.24/pushdown.md, website/versioned_docs/version-v2.1/configuration/flags.md, website/versioned_docs/version-v2.1/guides/full-text-search.mdx, website/versioned_docs/version-v2.1/guides/ttl-indexes.mdx, website/versioned_docs/version-v2.1/guides/vector-search.mdx, website/versioned_docs/version-v2.2/configuration/flags.md, website/versioned_docs/version-v2.2/guides/full-text-search.mdx, website/versioned_docs/version-v2.2/guides/ttl-indexes.mdx, website/versioned_docs/version-v2.2/guides/vector-search.mdx
Markdownlint does not really support MDX, and all MDX components are treated as HTML. On the other hand, `<!--` HTML comments syntax is invalid in MDX v2/v3.
=> Disable Markdownlint rule that clashes with MDX

internal/util/logging/lazy.go, internal/util/logging/logging.go
=> Add helpers for lazy logging
